// Copyright (c) Aura development team - Licensed under GNU GPL
// For more information, see license file in the main folder

using System.Collections.Generic;
using System.Reflection;

namespace Melia.Shared.Network
{
	/// <summary>
	/// Packet op code enum
	/// </summary>
	public static class Op
	{
		public const int CB_LOGIN = 0x03; // Size: 4457
		public const int CB_LOGIN_BY_PASSPORT = 0x04; // Size: 1154
		public const int CB_LOGOUT = 0x05; // Size: 10
		public const int CB_START_BARRACK = 0x06; // Size: 11
		public const int CB_COMMANDER_CREATE = 0x07; // Size: 93
		public const int BC_COMMANDER_CREATE_SLOTID = 0x08; // Size: 11
		public const int CB_COMMANDER_DESTROY = 0x09; // Size: 18
		public const int CB_CHECK_CLIENT_INTEGRITY = 0x0A; // Size: 74
		public const int CB_CLIENT_INTEGRITY_FAIL = 0x0B; // Size: 1035
		public const int CB_START_GAME = 0x0C; // Size: 13
		public const int CB_BARRACKNAME_CHANGE = 0x0D; // Size: 74
		public const int CB_COMMANDER_MOVE = 0x0E; // Size: 31
		public const int CB_ECHO = 0x0F; // Size: 30
		public const int BC_LOGINOK = 0x10; // Size: 156
		public const int BC_CYOU_LOGIN_FAIL = 0x11; // Size: 10
		public const int BC_LOGIN_PACKET_RECEIVED = 0x12; // Size: 10
		public const int BC_LOGOUTOK = 0x13; // Size: 10
		public const int BC_COMMANDER_LIST = 0x14; // Size: 0
		public const int BC_COMMANDER_CREATE = 0x15; // Size: 362
		public const int BC_COMMANDER_DESTROY = 0x16; // Size: 11
		public const int BC_START_GAMEOK = 0x17; // Size: 37
		public const int BC_SINGLE_INFO = 0x18; // Size: 353
		public const int BC_MESSAGE = 0x19; // Size: 0
		public const int BC_ECHO = 0x1A; // Size: 30
		public const int BC_MYPAGE_MAP = 0x1B; // Size: 0
		public const int BC_BARRACKNAME_CHANGE = 0x1C; // Size: 79
		public const int CB_IES_MODIFY_INFO = 0x32; // Size: 0
		public const int BC_IES_MODIFY_INFO = 0x33; // Size: 0
		public const int BC_IES_MODIFY_LIST = 0x34; // Size: 0
		public const int CB_IES_REVISION_DELETE = 0x35; // Size: 0
		public const int BC_IES_REVISION_DELETE = 0x36; // Size: 0
		public const int CB_SCREENSHOT_HASH = 0x37; // Size: 42
		public const int CB_REQ_CHANNEL_TRAFFIC = 0x38; // Size: 14
		public const int CB_VISIT = 0x39; // Size: 74
		public const int CB_BUY_THEMA = 0x3A; // Size: 22
		public const int BC_ACCOUNT_PROP = 0x3B; // Size: 0
		public const int CB_CURRENT_BARRACK = 0x3C; // Size: 39
		public const int BC_NORMAL = 0x3D; // Size: 0
		public const int CB_POSE = 0x3E; // Size: 15
		public const int CB_PLACE_CMD = 0x3F; // Size: 46
		public const int CB_CHAT = 0x40; // Size: 0
		public const int BC_CHAT = 0x41; // Size: 0
		public const int CB_ECHO_NORMAL = 0x42; // Size: 0
		public const int CB_REQ_SLOT_PRICE = 0x43; // Size: 10
		public const int BC_REQ_SLOT_PRICE = 0x44; // Size: 14
		public const int CB_CHANGE_BARRACK_LAYER = 0x45; // Size: 22
		public const int CB_SELECT_BARRACK_LAYER = 0x46; // Size: 14
		public const int CB_JUMP = 0x47; // Size: 19
		public const int BC_JUMP = 0x48; // Size: 19
		public const int BC_SERVER_ENTRY = 0x49; // Size: 22
		public const int CB_PET_PC = 0x4A; // Size: 26
		public const int CB_PET_COMMAND = 0x4B; // Size: 27
		public const int CB_REQ_CHANGE_POSTBOX_STATE = 0x4C; // Size: 23
		public const int CB_REQ_GET_POSTBOX_ITEM = 0x4D; // Size: 1051
		public const int CB_REQ_POSTBOX_PAGE = 0x4E; // Size: 14
		public const int BC_WAIT_QUEUE_ORDER = 0x4F; // Size: 14
		public const int CB_CANCEL_SERVER_WAIT_QUEUE = 0x50; // Size: 10
		public const int CB_NGS = 0x51; // Size: 0
		public const int BC_NGS = 0x52; // Size: 0
		public const int CB_GEMSCOOL_PCINFO = 0x53; // Size: 1290
		public const int CB_NOT_AUTHORIZED_ADDON_LIST = 0x54; // Size: 1039
		public const int CB_DEBUG_LOG_FILE = 0x55; // Size: 0
		public const int ZC_TREASUREMARK_LIST_MAP = 0xD8; // Size: 0
		public const int CS_LOGIN = 0xB55; // Size: 91
		public const int SC_NORMAL = 0xB56; // Size: 0
		public const int SC_FROM_INTEGRATE = 0xB57; // Size: 0
		public const int CS_REGISTER_SNS_ID = 0xB58; // Size: 24
		public const int CS_REQ_SNS_PC_INFO = 0xB59; // Size: 0
		public const int CS_REQ_ADD_FRIEND = 0xB5A; // Size: 74
		public const int CS_REQ_BLOCK_FRIEND = 0xB5B; // Size: 74
		public const int CS_FRIEND_CMD = 0xB5C; // Size: 32
		public const int CS_FRIEND_SET_ADDINFO = 0xB5D; // Size: 168
		public const int CS_CHAT = 0xB5E; // Size: 0
		public const int CS_GROUP_CHAT_INVITE = 0xB5F; // Size: 114
		public const int CS_GROUP_CHAT_INVITE_BY_TAG = 0xB60; // Size: 26
		public const int CS_ALLOW_GROUP_CHAT_TAG_INVITE = 0xB61; // Size: 50
		public const int CS_REFRESH_GROUP_CHAT = 0xB62; // Size: 10
		public const int CS_CREATE_GROUP_CHAT = 0xB63; // Size: 10
		public const int CS_REQ_CHAT_HISTORY = 0xB64; // Size: 26
		public const int CS_REQ_OUT_ROOM = 0xB65; // Size: 18
		public const int CS_REQ_RELATED_PC_SESSION = 0xB66; // Size: 24
		public const int CS_REDIS_SKILLPOINT = 0xB67; // Size: 26
		public const int CS_PARTY_CLIENT_INFO_SEND = 0xB68; // Size: 0
		public const int CS_NORMAL_GAME_START = 0xB69; // Size: 10
		public const int CS_REQUEST_PVP_RANKING = 0xB6A; // Size: 92
		public const int CS_REQUEST_ALL_SEASON_TOP_PVP_RANKING = 0xB6B; // Size: 84
		public const int CS_INVITE_PARTY_PVP = 0xB6C; // Size: 14
		public const int CS_ACCEPT_PARTY_PVP = 0xB6D; // Size: 23
		public const int CS_LIKE_IT = 0xB6E; // Size: 96
		public const int CS_UNLIKE_IT = 0xB6F; // Size: 32
		public const int CS_LIKE_IT_CONFIRM = 0xB70; // Size: 24
		public const int CS_ADD_RELATION_SCORE = 0xB71; // Size: 96
		public const int CS_GET_LIKE_COUNT = 0xB72; // Size: 24
		public const int CZ_CONNECT = 0xBB9; // Size: 1239
		public const int ZC_CONNECT_OK = 0xBBA; // Size: 0
		public const int ZC_MOVE_ZONE = 0xBBB; // Size: 11
		public const int CZ_MOVE_ZONE_OK = 0xBBC; // Size: 10
		public const int ZC_CONNECT_FAILED = 0xBBD; // Size: 0
		public const int CZ_GAME_READY = 0xBBE; // Size: 10
		public const int ZC_MOVE_ZONE_OK = 0xBBF; // Size: 61
		public const int CZ_LOGOUT = 0xBC0; // Size: 11
		public const int CZ_MOVE_BARRACK = 0xBC1; // Size: 11
		public const int ZC_MOVE_BARRACK = 0xBC2; // Size: 10
		public const int ZC_LOGOUT_OK = 0xBC3; // Size: 10
		public const int ZC_MESSAGE = 0xBC4; // Size: 0
		public const int ZC_RESET_VIEW = 0xBC5; // Size: 10
		public const int ZC_START_GAME = 0xBC6; // Size: 30
		public const int ZC_QUIET = 0xBC7; // Size: 11
		public const int ZC_ENTER_PC = 0xC1D; // Size: 366
		public const int ZC_ENTER_MONSTER = 0xC1E; // Size: 0
		public const int ZC_ENTER_DUMMYPC = 0xC1F; // Size: 328
		public const int ZC_UPDATED_DUMMYPC = 0xC20; // Size: 286
		public const int ZC_ENTER_ITEM = 0xC21; // Size: 107
		public const int ZC_LEAVE = 0xC22; // Size: 16
		public const int ZC_MOVE_PATH = 0xC23; // Size: 46
		public const int ZC_MOVE_POS = 0xC24; // Size: 47
		public const int ZC_MOVE_BEZIER = 0xC25; // Size: 79
		public const int ZC_MOVE_DIR = 0xC26; // Size: 44
		public const int ZC_EXPECTED_STOPPOS = 0xC27; // Size: 39
		public const int ZC_MSPD = 0xC28; // Size: 18
		public const int ZC_MOVE_SPEED = 0xC29; // Size: 23
		public const int ZC_MOVE_STOP = 0xC2A; // Size: 27
		public const int ZC_REST_SIT = 0xC2B; // Size: 16
		public const int ZC_JUMP = 0xC2C; // Size: 23
		public const int ZC_JUMP_DIR = 0xC2D; // Size: 38
		public const int ZC_ORDER_SKILL_JUMP = 0xC2E; // Size: 14
		public const int ZC_SKILL_JUMP = 0xC2F; // Size: 42
		public const int ZC_SET_POS = 0xC30; // Size: 27
		public const int ZC_FILE_MOVE = 0xC31; // Size: 50
		public const int CZ_LEAVE_TO_DUNGEON = 0xC32; // Size: 10
		public const int ZC_UPDATED_PCAPPEARANCE = 0xC33; // Size: 286
		public const int ZC_UPDATED_MONSTERAPPEARANCE = 0xC34; // Size: 0
		public const int ZC_CHAT = 0xC35; // Size: 0
		public const int ZC_CHAT_WITH_TEXTCODE = 0xC36; // Size: 18
		public const int ZC_STANCE_CHANGE = 0xC37; // Size: 18
		public const int ZC_ADD_HP = 0xC38; // Size: 26
		public const int ZC_SKILL_CAST_CANCEL = 0xC39; // Size: 14
		public const int ZC_SKILL_CAST = 0xC3A; // Size: 42
		public const int ZC_SKILL_READY = 0xC3B; // Size: 54
		public const int ZC_SKILL_DISABLE = 0xC3C; // Size: 19
		public const int ZC_SKILL_USE_CANCEL = 0xC3D; // Size: 14
		public const int ZC_SKILL_MELEE_TARGET = 0xC3E; // Size: 0
		public const int ZC_SKILL_MELEE_GROUND = 0xC3F; // Size: 0
		public const int ZC_SKILL_FORCE_TARGET = 0xC40; // Size: 0
		public const int ZC_SKILL_FORCE_GROUND = 0xC41; // Size: 0
		public const int ZC_SKILL_HIT_INFO = 0xC42; // Size: 0
		public const int ZC_BUFF_LIST = 0xC43; // Size: 0
		public const int ZC_BUFF_ADD = 0xC44; // Size: 0
		public const int ZC_BUFF_UPDATE = 0xC45; // Size: 0
		public const int ZC_BUFF_REMOVE = 0xC46; // Size: 24
		public const int ZC_BUFF_CLEAR = 0xC47; // Size: 15
		public const int CZ_BUFF_REMOVE = 0xC48; // Size: 14
		public const int CZ_INTE_WARP = 0xC49; // Size: 14
		public const int ZC_ROTATE = 0xC4A; // Size: 24
		public const int ZC_ROTATE_RESERVED = 0xC4B; // Size: 22
		public const int ZC_HEAD_ROTATE = 0xC4C; // Size: 22
		public const int ZC_TARGET_ROTATE = 0xC4D; // Size: 22
		public const int ZC_QUICK_ROTATE = 0xC4E; // Size: 22
		public const int ZC_POSE = 0xC4F; // Size: 38
		public const int ZC_DEAD = 0xC50; // Size: 0
		public const int ZC_RESURRECT = 0xC51; // Size: 22
		public const int ZC_CHANGE_RELATION = 0xC52; // Size: 15
		public const int ZC_RESURRECT_DIALOG = 0xC53; // Size: 14
		public const int ZC_HIT_INFO = 0xC54; // Size: 69
		public const int ZC_HEAL_INFO = 0xC55; // Size: 34
		public const int ZC_CAUTION_DAMAGE_INFO = 0xC57; // Size: 19
		public const int ZC_CAUTION_DAMAGE_RELEASE = 0xC58; // Size: 14
		public const int ZC_KNOCKBACK_INFO = 0xC59; // Size: 74
		public const int ZC_KNOCKDOWN_INFO = 0xC5A; // Size: 75
		public const int CZ_RESURRECT = 0xC5B; // Size: 19
		public const int ZC_RESURRECT_SAVE_POINT_ACK = 0xC5C; // Size: 11
		public const int ZC_RESURRECT_HERE_ACK = 0xC5D; // Size: 11
		public const int CZ_CLICK_TRIGGER = 0xC5E; // Size: 15
		public const int CZ_KEYBOARD_MOVE = 0xC5F; // Size: 41
		public const int CZ_EXPECTED_STOP_POS = 0xC60; // Size: 31
		public const int CZ_JUMP = 0xC61; // Size: 11
		public const int CZ_DASHRUN = 0xC62; // Size: 12
		public const int CZ_SKILL_JUMP_REQ = 0xC63; // Size: 30
		public const int CZ_MOVE_PATH = 0xC64; // Size: 27
		public const int CZ_MOVE_STOP = 0xC65; // Size: 35
		public const int CZ_REST_SIT = 0xC66; // Size: 10
		public const int CZ_REQ_CHAR_SLOT = 0xC67; // Size: 11
		public const int CZ_ON_AIR = 0xC68; // Size: 10
		public const int CZ_ON_GROUND = 0xC69; // Size: 10
		public const int CZ_MOVEMENT_INFO = 0xC6A; // Size: 23
		public const int CZ_SKILL_TARGET = 0xC6B; // Size: 19
		public const int CZ_SKILL_TARGET_ANI = 0xC6C; // Size: 23
		public const int CZ_SKILL_GROUND = 0xC6D; // Size: 61
		public const int CZ_SKILL_SELF = 0xC6E; // Size: 35
		public const int CZ_SKILL_CANCEL = 0xC6F; // Size: 12
		public const int CZ_HOLD = 0xC70; // Size: 11
		public const int CZ_ROTATE = 0xC71; // Size: 18
		public const int CZ_HEAD_ROTATE = 0xC72; // Size: 18
		public const int CZ_TARGET_ROTATE = 0xC73; // Size: 18
		public const int CZ_POSE = 0xC74; // Size: 34
		public const int CZ_CHAT = 0xC75; // Size: 0
		public const int CZ_SELF_CHAT = 0xC76; // Size: 0
		public const int CZ_CHAT_LOG = 0xC77; // Size: 0
		public const int CZ_SHOUT = 0xC78; // Size: 0
		public const int CZ_ITEM_DROP = 0xC79; // Size: 22
		public const int CZ_ITEM_DELETE = 0xC7A; // Size: 0
		public const int CZ_ITEM_USE = 0xC7B; // Size: 22
		public const int CZ_ITEM_USE_TO_ITEM = 0xC7C; // Size: 30
		public const int CZ_ITEM_USE_TO_GROUND = 0xC7D; // Size: 30
		public const int CZ_ITEM_BUY = 0xC7E; // Size: 0
		public const int CZ_ITEM_SELL = 0xC7F; // Size: 0
		public const int CZ_ITEM_EQUIP = 0xC80; // Size: 19
		public const int CZ_ITEM_UNEQUIP = 0xC81; // Size: 11
		public const int CZ_REQ_DELETE_EXPIRED_ITEMS = 0xC82; // Size: 18
		public const int ZC_CHECK_INVINDEX = 0xC83; // Size: 34
		public const int CZ_PREMIUM_ENCHANTCHIP = 0xC84; // Size: 26
		public const int CZ_PREMIUM_GACHACUBE = 0xC85; // Size: 10
		public const int ZC_ITEM_INVENTORY_LIST = 0xC86; // Size: 0
		public const int ZC_ITEM_INVENTORY_DIVISION_LIST = 0xC87; // Size: 0
		public const int ZC_ITEM_INVENTORY_INDEX_LIST = 0xC88; // Size: 0
		public const int ZC_ITEM_EQUIP_LIST = 0xC89; // Size: 0
		public const int ZC_ITEM_ADD = 0xC8A; // Size: 0
		public const int ZC_ITEM_REMOVE = 0xC8B; // Size: 24
		public const int ZC_ITEM_USE = 0xC8C; // Size: 18
		public const int ZC_ITEM_USE_TO_GROUND = 0xC8D; // Size: 26
		public const int ZC_QUICK_SLOT_LIST = 0xC8E; // Size: 0
		public const int ZC_SKILL_LIST = 0xC8F; // Size: 0
		public const int ZC_SKILL_ADD = 0xC90; // Size: 0
		public const int ZC_ABILITY_LIST = 0xC91; // Size: 0
		public const int CZ_REQ_OPEN_ITEM_DUNGEON = 0xC92; // Size: 19
		public const int CZ_ANSWER_OPEN_ITEM_DUNGEON = 0xC93; // Size: 19
		public const int CZ_SEND_ITEM_PROP_TO_ALCHMIST = 0xC94; // Size: 28
		public const int CZ_EXCUTE_ITEM_DUNGEON = 0xC95; // Size: 34
		public const int ZC_RECIVE_ITEM_PROP_TO_TARGET = 0xC96; // Size: 0
		public const int CZ_DISPEL_DEBUFF_TOGGLE = 0xC97; // Size: 14
		public const int CZ_JUNGTAN_TOGGLE = 0xC98; // Size: 24
		public const int ZC_EXP_UP = 0xC99; // Size: 26
		public const int ZC_EXP_UP_BY_MONSTER = 0xC9A; // Size: 30
		public const int ZC_PC_LEVELUP = 0xC9B; // Size: 18
		public const int ZC_PC_STAT_AVG = 0xC9C; // Size: 34
		public const int ZC_MAX_EXP_CHANGED = 0xC9D; // Size: 38
		public const int ZC_TEXT = 0xC9E; // Size: 0
		public const int ZC_UPDATE_SP = 0xC9F; // Size: 19
		public const int ZC_RESTORATION = 0xCA0; // Size: 16
		public const int ZC_UPDATE_MHP = 0xCA1; // Size: 18
		public const int CZ_DIALOG_ACK = 0xCA2; // Size: 14
		public const int CZ_DIALOG_SELECT = 0xCA3; // Size: 11
		public const int CZ_DIALOG_STRINGINPUT = 0xCA4; // Size: 138
		public const int ZC_DIALOG_OK = 0xCA5; // Size: 0
		public const int ZC_DIALOG_NEXT = 0xCA6; // Size: 0
		public const int ZC_DIALOG_SELECT = 0xCA7; // Size: 0
		public const int ZC_DIALOG_ITEM_SELECT = 0xCA8; // Size: 0
		public const int ZC_DIALOG_CLOSE = 0xCA9; // Size: 10
		public const int ZC_DIALOG_TRADE = 0xCAA; // Size: 43
		public const int ZC_DIALOG_COMMON_TRADE = 0xCAB; // Size: 43
		public const int ZC_DIALOG_NUMBERRANGE = 0xCAC; // Size: 0
		public const int ZC_DIALOG_STRINGINPUT = 0xCAD; // Size: 0
		public const int ZC_ADDON_MSG = 0xCAE; // Size: 0
		public const int CZ_UI_EVENT = 0xCAF; // Size: 0
		public const int ZC_PLAY_SOUND = 0xCB0; // Size: 19
		public const int ZC_STOP_SOUND = 0xCB1; // Size: 18
		public const int ZC_PLAY_MUSICQUEUE = 0xCB2; // Size: 18
		public const int ZC_STOP_MUSICQUEUE = 0xCB3; // Size: 18
		public const int ZC_PLAY_ANI = 0xCB4; // Size: 28
		public const int ZC_PLAY_ANI_SELFISH = 0xCB5; // Size: 23
		public const int ZC_CHANGE_ANI = 0xCB6; // Size: 48
		public const int CZ_MOVE_CAMP = 0xCB7; // Size: 18
		public const int CZ_CAMPINFO = 0xCB8; // Size: 18
		public const int ZC_CAMPINFO = 0xCB9; // Size: 22
		public const int ZC_FIX_ANIM = 0xCBA; // Size: 18
		public const int CZ_TARGET_JOB_INFO = 0xCBB; // Size: 18
		public const int ZC_TARGET_JOB_INFO = 0xCBC; // Size: 18
		public const int ZC_MOVE_ANIM = 0xCBD; // Size: 16
		public const int ZC_STD_ANIM = 0xCBE; // Size: 15
		public const int ZC_PLAY_ALARMSOUND = 0xCC0; // Size: 87
		public const int ZC_STOP_ALARMSOUND = 0xCC1; // Size: 14
		public const int ZC_PLAY_EXP_TEXT = 0xCC2; // Size: 18
		public const int ZC_PLAY_NAVI_EFFECT = 0xCC3; // Size: 154
		public const int ZC_UPDATE_ALL_STATUS = 0xCC4; // Size: 30
		public const int ZC_OBJECT_PROPERTY = 0xCC5; // Size: 0
		public const int ZC_DUMP_PROPERTY = 0xCC6; // Size: 0
		public const int ZC_SHOUT = 0xCC7; // Size: 0
		public const int ZC_SHOUT_FAILED = 0xCC8; // Size: 11
		public const int CZ_EXCHANGE_REQUEST = 0xCC9; // Size: 14
		public const int ZC_EXCHANGE_REQUEST_ACK = 0xCCA; // Size: 76
		public const int ZC_EXCHANGE_REQUEST_RECEIVED = 0xCCB; // Size: 75
		public const int CZ_EXCHANGE_ACCEPT = 0xCCC; // Size: 10
		public const int CZ_EXCHANGE_DECLINE = 0xCCD; // Size: 10
		public const int ZC_EXCHANGE_DECLINE_ACK = 0xCCE; // Size: 10
		public const int ZC_EXCHANGE_START = 0xCCF; // Size: 76
		public const int CZ_EXCHANGE_OFFER = 0xCD0; // Size: 30
		public const int ZC_EXCHANGE_OFFER_ACK = 0xCD1; // Size: 0
		public const int CZ_EXCHANGE_AGREE = 0xCD2; // Size: 10
		public const int ZC_EXCHANGE_AGREE_ACK = 0xCD3; // Size: 11
		public const int CZ_EXCHANGE_FINALAGREE = 0xCD4; // Size: 10
		public const int ZC_EXCHANGE_FINALAGREE_ACK = 0xCD5; // Size: 11
		public const int CZ_EXCHANGE_CANCEL = 0xCD6; // Size: 10
		public const int ZC_EXCHANGE_CANCEL_ACK = 0xCD7; // Size: 10
		public const int ZC_EXCHANGE_SUCCESS = 0xCD8; // Size: 10
		public const int ZC_COOLDOWN_LIST = 0xCD9; // Size: 0
		public const int ZC_COOLDOWN_CHANGED = 0xCDA; // Size: 31
		public const int ZC_OVERHEAT_CHANGED = 0xCDB; // Size: 34
		public const int ZC_TEST_AGENT = 0xCDC; // Size: 22
		public const int CZ_COMMON_SHOP_LIST = 0xCDD; // Size: 10
		public const int ZC_COMMON_SHOP_LIST = 0xCDE; // Size: 12
		public const int ZC_TIME_FACTOR = 0xCDF; // Size: 14
		public const int ZC_PARTY_ENTER = 0xCE0; // Size: 0
		public const int ZC_PARTY_OUT = 0xCE1; // Size: 28
		public const int ZC_PARTY_DESTROY = 0xCE2; // Size: 19
		public const int ZC_PARTY_INFO = 0xCE3; // Size: 0
		public const int ZC_PARTY_LIST = 0xCE4; // Size: 0
		public const int ZC_PARTY_CHAT = 0xCE5; // Size: 0
		public const int ZC_PARTY_INST_INFO = 0xCE6; // Size: 0
		public const int ZC_CHANGE_EQUIP_DURABILITY = 0xCE7; // Size: 15
		public const int CZ_DIALOG_TX = 0xCE8; // Size: 0
		public const int CZ_REQ_RECIPE = 0xCE9; // Size: 0
		public const int ZC_CUSTOM_DIALOG = 0xCEA; // Size: 79
		public const int ZC_SESSION_OBJECTS = 0xCEB; // Size: 0
		public const int ZC_SESSION_OBJ_ADD = 0xCEC; // Size: 0
		public const int ZC_SESSION_OBJ_REMOVE = 0xCED; // Size: 14
		public const int ZC_SESSION_OBJ_TIME = 0xCEE; // Size: 18
		public const int CZ_S_OBJ_VALUE_C = 0xCEF; // Size: 26
		public const int CZ_REQ_NORMAL_TX = 0xCF0; // Size: 45
		public const int ZC_COMMANDER_LOADER_INFO = 0xCF1; // Size: 0
		public const int ZC_MOVE_SINGLE_ZONE = 0xCF2; // Size: 22
		public const int ZC_BACKTO_ORIGINAL_SERVER = 0xCF3; // Size: 12
		public const int CZ_BACKTO_ORIGINAL_SERVER = 0xCF4; // Size: 12
		public const int CZ_REQ_NORMAL_TX_NUMARG = 0xCF5; // Size: 0
		public const int ZC_UI_OPEN = 0xCF6; // Size: 43
		public const int ZC_ENABLE_CONTROL = 0xCF7; // Size: 79
		public const int ZC_CHANGE_CAMERA = 0xCF8; // Size: 35
		public const int ZC_MONSTER_SDR_CHANGED = 0xCF9; // Size: 15
		public const int ZC_MOVE_IGNORE_COLLISION = 0xCFA; // Size: 34
		public const int ZC_CHANGE_CAMERA_ZOOM = 0xCFB; // Size: 38
		public const int ZC_PLAY_SKILL_ANI = 0xCFC; // Size: 86
		public const int ZC_PLAY_SKILL_CAST_ANI = 0xCFD; // Size: 34
		public const int CZ_REQ_ITEM_GET = 0xCFE; // Size: 14
		public const int ZC_ITEM_GET = 0xCFF; // Size: 22
		public const int CZ_GUARD = 0xD00; // Size: 19
		public const int ZC_GUARD = 0xD01; // Size: 23
		public const int ZC_STAMINA = 0xD02; // Size: 14
		public const int ZC_ADD_STAMINA = 0xD03; // Size: 14
		public const int ZC_GM_ORDER = 0xD04; // Size: 14
		public const int ZC_MYPC_ENTER = 0xD05; // Size: 23
		public const int ZC_LOCK_KEY = 0xD06; // Size: 79
		public const int ZC_SAVE_INFO = 0xD07; // Size: 10
		public const int CZ_SAVE_INFO = 0xD08; // Size: 0
		public const int ZC_OPTION_LIST = 0xD09; // Size: 0
		public const int ZC_SKILLMAP_LIST = 0xD0A; // Size: 0
		public const int CZ_GIVEITEM_TO_DUMMYPC = 0xD0B; // Size: 22
		public const int CZ_FOOD_TABLE_TITLE = 0xD0C; // Size: 79
		public const int CZ_USE_TP_AND_ENTER_INDUN = 0xD0D; // Size: 522
		public const int CZ_USE_RANKRESET_ITEM = 0xD0E; // Size: 18
		public const int CZ_REQ_RANKRESET_SYSTEM = 0xD0F; // Size: 19
		public const int ZC_SET_LAYER = 0xD10; // Size: 15
		public const int ZC_CREATE_LAYERBOX = 0xD11; // Size: 42
		public const int ZC_RESET_BOX = 0xD12; // Size: 15
		public const int ZC_CREATE_SCROLLLOCKBOX = 0xD13; // Size: 42
		public const int ZC_REMOVE_SCROLLLOCKBOX = 0xD14; // Size: 14
		public const int CZ_DYNAMIC_CASTING_START = 0xD15; // Size: 25
		public const int CZ_DYNAMIC_CASTING_END = 0xD16; // Size: 20
		public const int CZ_SKILL_CANCEL_SCRIPT = 0xD17; // Size: 10
		public const int ZC_LEAVE_TRIGGER = 0xD18; // Size: 10
		public const int ZC_BORN = 0xD19; // Size: 14
		public const int ZC_ACHIEVE_POINT_LIST = 0xD1A; // Size: 0
		public const int ZC_ACHIEVE_POINT = 0xD1B; // Size: 22
		public const int CZ_ACHIEVE_EQUIP = 0xD1C; // Size: 14
		public const int ZC_ACHIEVE_EQUIP = 0xD1D; // Size: 22
		public const int CZ_ACHIEVE_REWARD = 0xD1E; // Size: 14
		public const int CZ_CHANGE_CONFIG = 0xD1F; // Size: 18
		public const int CZ_CHANGE_CONFIG_STR = 0xD20; // Size: 34
		public const int ZC_WORLD_MSG = 0xD21; // Size: 47
		public const int ZC_ENABLE_SHOW_ITEM_GET = 0xD22; // Size: 12
		public const int ZC_LOGIN_TIME = 0xD23; // Size: 18
		public const int ZC_GIVE_EXP_TO_PC = 0xD24; // Size: 50
		public const int ZC_LAYER_PC_LIST = 0xD25; // Size: 0
		public const int ZC_LAYER_PC_SOBJ_PROP = 0xD26; // Size: 0
		public const int CZ_CUSTOM_COMMAND = 0xD27; // Size: 26
		public const int ZC_LAYER_INFO = 0xD28; // Size: 14
		public const int CZ_CHAT_MACRO = 0xD29; // Size: 146
		public const int ZC_CHAT_MACRO_LIST = 0xD2A; // Size: 0
		public const int ZC_RULLET_LIST = 0xD2B; // Size: 0
		public const int ZC_QUICKSLOT_REGISTER = 0xD2C; // Size: 50
		public const int CZ_QUICKSLOT_LIST = 0xD2D; // Size: 0
		public const int CZ_DOUBLE_ITEM_EQUIP = 0xD2E; // Size: 28
		public const int ZC_TRICK_PACKET = 0xD2F; // Size: 0
		public const int ZC_COOLDOWN_RATE = 0xD30; // Size: 26
		public const int ZC_MAP_REVEAL_LIST = 0xD31; // Size: 0
		public const int CZ_MAP_REVEAL_INFO = 0xD32; // Size: 146
		public const int CZ_MAP_SEARCH_INFO = 0xD33; // Size: 55
		public const int ZC_EXEC_CLIENT_SCP = 0xD34; // Size: 0
		public const int ZC_SET_NPC_STATE = 0xD35; // Size: 22
		public const int ZC_NPC_STATE_LIST = 0xD36; // Size: 0
		public const int CZ_QUEST_NPC_STATE_CHECK = 0xD37; // Size: 14
		public const int ZC_RANK_ACHIEVE_ADD = 0xD38; // Size: 18
		public const int CZ_IES_MODIFY_INFO = 0xD39; // Size: 0
		public const int ZC_IES_MODIFY_INFO = 0xD3A; // Size: 0
		public const int ZC_IES_MODIFY_LIST = 0xD3B; // Size: 0
		public const int CZ_IES_REVISION_DELETE = 0xD3C; // Size: 0
		public const int ZC_IES_REVISION_DELETE = 0xD3D; // Size: 0
		public const int ZC_EQUIP_ITEM_REMOVE = 0xD3E; // Size: 22
		public const int ZC_SOLD_ITEM_LIST = 0xD3F; // Size: 0
		public const int ZC_SOLD_ITEM_DIVISION_LIST = 0xD40; // Size: 0
		public const int CZ_SOLD_ITEM = 0xD41; // Size: 19
		public const int CZ_WAREHOUSE_CMD = 0xD42; // Size: 32
		public const int CZ_SWAP_ETC_INV_CHANGE_INDEX = 0xD43; // Size: 35
		public const int CZ_SORT_INV = 0xD44; // Size: 12
		public const int CZ_EXTEND_WAREHOUSE = 0xD45; // Size: 11
		public const int CZ_CAST_CONTROL_SHOT = 0xD46; // Size: 10
		public const int ZC_PC_PROP_UPDATE = 0xD47; // Size: 15
		public const int CZ_CLIENT_DAMAGE = 0xD48; // Size: 14
		public const int CZ_CLIENT_ATTACK = 0xD49; // Size: 15
		public const int ZC_SYSTEM_MSG = 0xD4A; // Size: 0
		public const int ZC_FSM_MOVE = 0xD4B; // Size: 0
		public const int CZ_QUEST_CHECK_SAVE = 0xD4C; // Size: 50
		public const int CZ_SPRAY_REQ_INFO = 0xD4D; // Size: 14
		public const int CZ_SPRAY_DRAW_INFO = 0xD4E; // Size: 0
		public const int ZC_SPRAY_ID = 0xD4F; // Size: 22
		public const int ZC_SPRAY_DRAW_INFO = 0xD50; // Size: 0
		public const int ZC_MONSTER_LIFETIME = 0xD51; // Size: 18
		public const int ZC_SPRAY_LIKE_LIST = 0xD52; // Size: 0
		public const int ZC_SHARED_MSG = 0xD53; // Size: 14
		public const int CZ_REQ_TX_ITEM = 0xD54; // Size: 0
		public const int ZC_TEST_DBG = 0xD55; // Size: 0
		public const int ZC_MONSTER_DIST = 0xD56; // Size: 0
		public const int ZC_RESET_SKILL_FORCEID = 0xD57; // Size: 14
		public const int ZC_EMOTICON = 0xD58; // Size: 22
		public const int ZC_SHOW_EMOTICON = 0xD59; // Size: 22
		public const int ZC_TREASUREMARK_BY_MAP = 0xD5A; // Size: 0
		public const int ZC_SHOW_MAP = 0xD5B; // Size: 0
		public const int CZ_FLEE_OBSTACLE = 0xD5C; // Size: 26
		public const int ZC_HOLD_MOVE_PATH = 0xD5D; // Size: 15
		public const int ZC_ENTER_HOOK = 0xD5E; // Size: 14
		public const int ZC_LEAVE_HOOK = 0xD5F; // Size: 14
		public const int ZC_MONSTER_PROPERTY = 0xD60; // Size: 0
		public const int ZC_GROUND_EFFECT = 0xD61; // Size: 54
		public const int ZC_FLY = 0xD62; // Size: 22
		public const int ZC_FLY_OPTION = 0xD63; // Size: 18
		public const int ZC_FLY_MATH = 0xD64; // Size: 27
		public const int ZC_FLY_HEIGHT = 0xD65; // Size: 18
		public const int ZC_UPDATE_SHIELD = 0xD66; // Size: 18
		public const int ZC_SHOW_MODEL = 0xD67; // Size: 19
		public const int ZC_SKILL_RANGE_DBG = 0xD68; // Size: 62
		public const int ZC_SKILL_RANGE_FAN = 0xD69; // Size: 44
		public const int ZC_SKILL_RANGE_SQUARE = 0xD6A; // Size: 44
		public const int ZC_SKILL_RANGE_CIRCLE = 0xD6B; // Size: 32
		public const int ZC_SKILL_RANGE_DONUTS = 0xD6C; // Size: 36
		public const int ZC_TEAMID = 0xD6D; // Size: 15
		public const int ZC_PC = 0xD6E; // Size: 0
		public const int CZ_LOG = 0xD6F; // Size: 0
		public const int ZC_MOTIONBLUR = 0xD70; // Size: 15
		public const int ZC_PLAY_FORCE = 0xD71; // Size: 82
		public const int ZC_CAST_TARGET = 0xD72; // Size: 18
		public const int ZC_START_INFO = 0xD73; // Size: 0
		public const int ZC_JOB_EXP_UP = 0xD74; // Size: 26
		public const int ZC_JOB_PTS = 0xD75; // Size: 22
		public const int ZC_MON_STAMINA = 0xD76; // Size: 26
		public const int CZ_CUSTOM_SCP = 0xD77; // Size: 14
		public const int ZC_VIEW_FOCUS = 0xD78; // Size: 28
		public const int ZC_HARDCODED_SKILL = 0xD79; // Size: 30
		public const int CZ_HARDCODED_SKILL = 0xD7A; // Size: 34
		public const int ZC_FORCE_MOVE = 0xD7B; // Size: 34
		public const int ZC_HSKILL_CONTROL = 0xD7C; // Size: 26
		public const int ZC_CANCEL_DEADEVENT = 0xD7D; // Size: 14
		public const int ZC_ACTION_PKS = 0xD7E; // Size: 39
		public const int CZ_HARDCODED_ITEM = 0xD7F; // Size: 22
		public const int CZ_CANCEL_TRANSFORM_SKILL = 0xD80; // Size: 10
		public const int CZ_BRIQUET = 0xD81; // Size: 32
		public const int ZC_VIBRATE = 0xD82; // Size: 34
		public const int ZC_COUNTER_MOVE = 0xD83; // Size: 14
		public const int CZ_COUNTER_ATTACK = 0xD84; // Size: 14
		public const int CZ_CLIENT_DIRECT = 0xD85; // Size: 30
		public const int ZC_CLIENT_DIRECT = 0xD86; // Size: 34
		public const int ZC_OWNER = 0xD87; // Size: 18
		public const int ZC_GD_RANK = 0xD88; // Size: 14
		public const int CZ_RUN_BGEVENT = 0xD89; // Size: 74
		public const int ZC_ADD_SKILL_EFFECT = 0xD8A; // Size: 22
		public const int ZC_ITEM_DROPABLE = 0xD8B; // Size: 14
		public const int CZ_ITEM_DROP_TO_OBJECT = 0xD8C; // Size: 26
		public const int ZC_NORMAL = 0xD8D; // Size: 0
		public const int CZ_G_QUEST_CHECK = 0xD8E; // Size: 14
		public const int ZC_MOVE_PATH_MATH = 0xD8F; // Size: 34
		public const int CZ_MYPAGE_COMMENT_ADD = 0xD90; // Size: 278
		public const int CZ_MYPAGE_COMMENT_DELETE = 0xD91; // Size: 18
		public const int CZ_GUESTPAGE_COMMENT_ADD = 0xD92; // Size: 278
		public const int CZ_GET_TARGET_MYPAGE = 0xD93; // Size: 14
		public const int CZ_ON_MYPAGE_MODE = 0xD94; // Size: 14
		public const int CZ_RESET_SOCIAL_MODE = 0xD95; // Size: 10
		public const int CZ_GET_TARGET_GUESTPAGE = 0xD96; // Size: 14
		public const int CZ_ADD_SELLMODE_ITEM = 0xD97; // Size: 30
		public const int CZ_DELETE_SELLMODE_ITEM = 0xD98; // Size: 18
		public const int CZ_ON_SELLITEM_MODE = 0xD99; // Size: 14
		public const int ZC_MYPAGE_MAP = 0xD9A; // Size: 0
		public const int ZC_GUESTPAGE_MAP = 0xD9B; // Size: 0
		public const int ZC_ON_MYPAGE_MODE = 0xD9C; // Size: 0
		public const int ZC_RESET_SOCIAL_MODE = 0xD9D; // Size: 14
		public const int CZ_ON_ITEMBUY_MODE = 0xD9E; // Size: 0
		public const int ZC_ON_BUYITEM_MODE = 0xD9F; // Size: 0
		public const int ZC_SHOW_GROUND_ITEM_MARK = 0xDA0; // Size: 34
		public const int ZC_HELP_LIST = 0xDA1; // Size: 0
		public const int ZC_HELP_ADD = 0xDA2; // Size: 15
		public const int CZ_CLIENT_HIT_LIST = 0xDA3; // Size: 0
		public const int ZC_PC_ATKSTATE = 0xDA4; // Size: 15
		public const int ZC_SEND_PREMIUM_STATE = 0xDA5; // Size: 20
		public const int CZ_HELP_READ_TYPE = 0xDA6; // Size: 18
		public const int CZ_MOVE_PATH_END = 0xDA7; // Size: 10
		public const int ZC_COLL_DAMAGE = 0xDA8; // Size: 15
		public const int CZ_KEYBOARD_BEAT = 0xDA9; // Size: 10
		public const int CZ_MOVEHIT_SCP = 0xDAA; // Size: 22
		public const int ZC_SYNC_START = 0xDAB; // Size: 18
		public const int ZC_SYNC_END = 0xDAC; // Size: 18
		public const int ZC_SYNC_EXEC = 0xDAD; // Size: 14
		public const int ZC_SYNC_EXEC_BY_SKILL_TIME = 0xDAE; // Size: 22
		public const int CZ_STOP_TIMEACTION = 0xDAF; // Size: 11
		public const int CZ_REQ_DUMMYPC_INFO = 0xDB0; // Size: 18
		public const int CZ_VISIT_BARRACK = 0xDB1; // Size: 74
		public const int CZ_SPC_SKILL_POS = 0xDB2; // Size: 22
		public const int CZ_CHANGE_HEAD = 0xDB3; // Size: 74
		public const int CZ_CREATE_ARROW_CRAFT = 0xDB4; // Size: 14
		public const int CZ_EXCHANGE_ANTIQUE = 0xDB5; // Size: 22
		public const int CZ_REQ_MINITEXT = 0xDB6; // Size: 266
		public const int ZC_PC_MOVE_STOP = 0xDB7; // Size: 39
		public const int CZ_STOP_ALLPC = 0xDB8; // Size: 10
		public const int CZ_COMPLETE_PRELOAD = 0xDB9; // Size: 14
		public const int CZ_MGAME_JOIN_CMD = 0xDBA; // Size: 46
		public const int CZ_ADD_HELP = 0xDBB; // Size: 14
		public const int ZC_ATTACH_TO_OBJ = 0xDBC; // Size: 53
		public const int ZC_DETACH_FROM_OBJ = 0xDBD; // Size: 18
		public const int ZC_RUN_FROM = 0xDBE; // Size: 18
		public const int ZC_LOOKAT_OBJ = 0xDBF; // Size: 18
		public const int CZ_SKILL_CELL_LIST = 0xDC0; // Size: 0
		public const int CZ_SKILL_TOOL_GROUND_POS = 0xDC1; // Size: 26
		public const int CZ_DIRECTION_PROCESS = 0xDC2; // Size: 18
		public const int CZ_DIRECTION_MOVE_STATE = 0xDC3; // Size: 0
		public const int ZC_TO_ALL_CLIENT = 0xDC4; // Size: 0
		public const int ZC_TO_CLIENT = 0xDC5; // Size: 0
		public const int CZ_REWARD_CMD = 0xDC6; // Size: 14
		public const int CZ_PROPERTY_COMPARE = 0xDC7; // Size: 16
		public const int ZC_PROPERTY_COMPARE = 0xDC8; // Size: 0
		public const int ZC_PROPERTY_COMPARE_FOR_ACT = 0xDC9; // Size: 0
		public const int ZC_FACTION = 0xDCA; // Size: 18
		public const int ZC_SEND_CASH_VALUE = 0xDCB; // Size: 0
		public const int ZC_BEGIN_KILL_LOG = 0xDCC; // Size: 10
		public const int ZC_END_KILL_LOG = 0xDCD; // Size: 10
		public const int ZC_CLEAR_KILL_LOG = 0xDCE; // Size: 10
		public const int CZ_NPC_AUCTION_CMD = 0xDCF; // Size: 30
		public const int ZC_DIRECTION_APC = 0xDD0; // Size: 30
		public const int ZC_BGMODEL_ANIM_INFO = 0xDD1; // Size: 19
		public const int ZC_ATTACH_BY_KNOCKBACK = 0xDD2; // Size: 42
		public const int CZ_OBJECT_MOVE = 0xDD3; // Size: 30
		public const int CZ_CONTROL_OBJECT_ROTATE = 0xDD4; // Size: 22
		public const int CZ_SUMMON_COMMAND = 0xDD5; // Size: 18
		public const int CZ_VEHICLE_RIDE = 0xDD6; // Size: 15
		public const int CZ_REQ_ACHIEVE_RANK_PAGE_INFO = 0xDD7; // Size: 78
		public const int ZC_SPC_TRIGGER_EXEC = 0xDD8; // Size: 34
		public const int CZ_REQ_MGAME_VIEW = 0xDD9; // Size: 18
		public const int CZ_REQ_MGAME_CHAT = 0xDDA; // Size: 0
		public const int CZ_TOURNAMENT_GIFT = 0xDDB; // Size: 18
		public const int CZ_PARTY_INVITE_ACCEPT = 0xDDC; // Size: 87
		public const int CZ_PARTY_INVITE_CANCEL = 0xDDD; // Size: 91
		public const int CZ_PARTY_PROP_CHANGE = 0xDDE; // Size: 147
		public const int CZ_REQ_MARKET_REGISTER = 0xDDF; // Size: 40
		public const int CZ_REQ_MARKET_MINMAX_INFO = 0xDE0; // Size: 18
		public const int CZ_REQ_MARKET_BUY = 0xDE1; // Size: 0
		public const int CZ_REQ_MARKET_LIST = 0xDE2; // Size: 138
		public const int CZ_REQ_MY_SELL_LIST = 0xDE3; // Size: 14
		public const int CZ_REQ_CABINET_LIST = 0xDE4; // Size: 10
		public const int CZ_REQ_GET_CABINET_ITEM = 0xDE5; // Size: 26
		public const int CZ_REQ_CANCEL_MARKET_ITEM = 0xDE6; // Size: 18
		public const int CZ_INV_ITEM_LOCK = 0xDE7; // Size: 19
		public const int CZ_OBJ_RECORD_POS = 0xDE8; // Size: 0
		public const int CZ_FORMATION_CMD = 0xDE9; // Size: 32
		public const int CZ_REGISTER_AUTOSELLER = 0xDEA; // Size: 0
		public const int CZ_OPEN_AUTOSELLER = 0xDEB; // Size: 66
		public const int CZ_BUY_AUTOSELLER_ITEMS = 0xDEC; // Size: 0
		public const int CZ_SELL_MY_AUTOSELLER_ITEMS = 0xDED; // Size: 0
		public const int CZ_PUZZLE_CRAFT = 0xDEE; // Size: 0
		public const int CZ_PET_EQUIP = 0xDEF; // Size: 34
		public const int CZ_PET_AUTO_ATK = 0xDF0; // Size: 11
		public const int ZC_PET_AUTO_ATK = 0xDF1; // Size: 11
		public const int ZC_FOUND_PARTY_LIST = 0xDF2; // Size: 0
		public const int ZC_NEAR_PARTY_LIST = 0xDF3; // Size: 0
		public const int ZC_RECOMMEND_PARTY_INFO = 0xDF4; // Size: 0
		public const int CZ_REQUEST_SOME_PARTY = 0xDF5; // Size: 90
		public const int CZ_REFRESH_MEMBERRECOMMEND_LIST = 0xDF6; // Size: 10
		public const int ZC_TO_SOMEWHERE_CLIENT = 0xDF7; // Size: 0
		public const int CZ_REVEAL_NPC_STATE = 0xDF8; // Size: 14
		public const int CZ_CHANGE_CHANNEL = 0xDF9; // Size: 12
		public const int CZ_REQ_CHANNEL_TRAFFICS = 0xDFA; // Size: 12
		public const int CZ_BUY_PROPERTYSHOP_ITEM = 0xDFB; // Size: 0
		public const int CZ_SKILL_USE_HEIGHT = 0xDFC; // Size: 14
		public const int CZ_CHANGE_GUILD_NEUTRALITY = 0xDFD; // Size: 10
		public const int CZ_SAVE_GUILD_BOARD = 0xDFE; // Size: 110
		public const int CZ_DELETE_PARTY_EVENT = 0xDFF; // Size: 20
		public const int CZ_PING = 0xE00; // Size: 10
		public const int ZC_PING = 0xE01; // Size: 10
		public const int CZ_REQ_REMAIN_NEXONCASH = 0xE02; // Size: 10
		public const int CZ_REQ_OPEN_INGAMESHOP_UI = 0xE03; // Size: 10
		public const int CZ_REQ_BUY_INGAMESHOP_ITEM = 0xE04; // Size: 78
		public const int CZ_REQ_BUY_ALL_INGAMESHOP_ITEM = 0xE05; // Size: 10
		public const int CZ_REQ_PICKUP_CASHITEM = 0xE06; // Size: 37
		public const int CZ_REQ_REFUND_CASHITEM = 0xE07; // Size: 33
		public const int ZC_XIGNCODE_BUFFER = 0xE08; // Size: 524
		public const int CZ_XIGNCODE_BUFFER = 0xE09; // Size: 524
		public const int CZ_SYSTEM_LOG_SAVE_TO_MONGODB = 0xE0A; // Size: 280
		public const int CZ_CHANGE_TITLE = 0xE0B; // Size: 74
		public const int CZ_PC_COMMENT_CHANGE = 0xE0C; // Size: 0
		public const int CZ_AUTTOSELLER_BUYER_CLOSE = 0xE0D; // Size: 18
		public const int CZ_REQ_ITEM_LIST = 0xE0E; // Size: 11
		public const int CZ_REQ_ACC_WARE_VIS_LOG = 0xE0F; // Size: 10
		public const int CZ_HIT_MISSILE = 0xE10; // Size: 14
		public const int CZ_I_NEED_PARTY = 0xE11; // Size: 23
		public const int CZ_PARTY_JOIN_BY_LINK = 0xE12; // Size: 19
		public const int ZC_RECOMMEND_PARTYMEMBER_INFO = 0xE13; // Size: 0
		public const int CZ_PVP_ZONE_CMD = 0xE14; // Size: 26
		public const int CZ_PVP_CHAT = 0xE15; // Size: 0
		public const int CZ_CARDBATTLE_CMD = 0xE16; // Size: 26
		public const int CZ_REQ_UPDATE_CONTENTS_SESSION = 0xE17; // Size: 10
		public const int CZ_REQ_FRIENDLY_FIGHT = 0xE18; // Size: 15
		public const int CZ_HARDSKILL_POS_LIST = 0xE19; // Size: 0
		public const int CZ_CART_POSITION = 0xE1A; // Size: 26
		public const int CZ_REQ_RIDE_CART = 0xE1B; // Size: 18
		public const int CZ_DUMMYPC_SKILL_POS = 0xE1C; // Size: 26
		public const int CZ_NGS = 0xE1D; // Size: 0
		public const int ZC_NGS = 0xE1E; // Size: 0
		public const int CZ_PARTY_MEMBER_SKILL_USE = 0xE1F; // Size: 0
		public const int CZ_PARTY_MEMBER_SKILL_ACCEPT = 0xE20; // Size: 23
		public const int CZ_SYSTEM_LOG_TO_SERVER = 0xE21; // Size: 1099
		public const int CZ_CHECK_PING = 0xE22; // Size: 16
		public const int CZ_CANCEL_INDUN_MATCHING = 0xE23; // Size: 10
		public const int CZ_CANCEL_INDUN_PARTY_MATCHING = 0xE24; // Size: 10
		public const int CZ_REQ_GM_ORDER = 0xE25; // Size: 202
		public const int CZ_REPORT_AUTOBOT = 0xE26; // Size: 74
		public const int CZ_REPORT_PVP_ZOOM = 0xE27; // Size: 10
		public const int CZ_PARTY_INVENTORY_LOAD = 0xE28; // Size: 12
		public const int CZ_PARTY_SHARED_QUEST = 0xE29; // Size: 278
		public const int CZ_REQ_MOVE_PARTYINV_TO_ACCOUNT = 0xE2A; // Size: 0
		public const int CZ_PVP_COMMAND = 0xE2B; // Size: 23
		public const int CZ_REQ_CancelGachaCube = 0xE2C; // Size: 10
		public const int CZ_WAREHOUSE_TAKE_LIST = 0xE2D; // Size: 0
		public const int CZ_SAVE_AUTO_MACRO = 0xE2E; // Size: 0
		public const int CZ_REQUEST_LOAD_ITEM_BUY_LIMIT = 0xE2F; // Size: 10
		public const int CZ_AUTO_STATE = 0xE30; // Size: 11
		public const int CZ_RUN_GAMEEXIT_TIMER = 0xE31; // Size: 42
		public const int CZ_FIXED_NOTICE_SHOW = 0xE32; // Size: 10
		public const int CZ_SAGE_SKILL_GO_FRIEND = 0xE33; // Size: 90
		public const int CZ_REQUEST_CHANGE_NAME = 0xE34; // Size: 66
		public const int CZ_REQUEST_CHANGE_PET_NAME = 0xE35; // Size: 50
		public const int CZ_CYOU_CTU_CLIENT_MSG = 0xE36; // Size: 1054
		public const int ZC_CYOU_KICK_USER_EXIT_CLIENT = 0xE38; // Size: 10
		public const int ZC_HOLD_EXP_BOOK_TIME = 0xE39; // Size: 25
		public const int CZ_HOLD_EXP_BOOK_TIME = 0xE3A; // Size: 14
		public const int CZ_SCREENSHOT_HASH = 0xE3B; // Size: 43
		public const int CZ_REQ_MOVE_TO_INDUN = 0xE3C; // Size: 18
		public const int CZ_CLEAR_INDUN_REG = 0xE3D; // Size: 10
		public const int CZ_REQ_REGISTER_TO_INDUN = 0xE3E; // Size: 14
		public const int CZ_REQ_GUILD_MEMBER_AUTHORITY = 0xE3F; // Size: 23
		public const int CZ_TPSHOP_RTPP_FOR_TEST = 0xE40; // Size: 10
		public const int CZ_REQ_FORGERY = 0xE41; // Size: 30
		public const int CZ_REQ_UNDERSTAFF_ENTER_ALLOW = 0xE42; // Size: 10
		public const int CZ_REQ_UNDERSTAFF_ENTER_ALLOW_WITH_PARTY = 0xE43; // Size: 14
		public const int CZ_REQ_BUILD_FOODTABLE = 0xE44; // Size: 79
		public const int ZC_PLAY_PAIR_ANIMATION = 0xE45; // Size: 38
		public const int CZ_REQ_FISHING = 0xE46; // Size: 23
		public const int CZ_REQ_GET_FISHING_ITEM = 0xE47; // Size: 10
		public const int ZC_PLAY_ATTACH_MODEL_ANIM = 0xE48; // Size: 26
		public const int CZ_RUN_FUNCTION_DUMP = 0xE49; // Size: 0
		public const int ZC_RUN_FUNCTION_DUMP = 0xE4A; // Size: 0
		public const int ZC_RUN_FUNCTION_DUMP_ERROR = 0xE4B; // Size: 0
		public const int ZC_RUN_FUNCTION_DUMP_PRINT = 0xE4C; // Size: 0
		public const int ZC_ATTACH_TO_SLOT = 0xE4D; // Size: 26
		public const int ZC_FISHING_ITEM_LIST = 0xE4E; // Size: 0
		public const int CZ_REQ_FISHING_RANK = 0xE4F; // Size: 78
		public const int ZC_ENABLE_ROTATE = 0xE50; // Size: 79
		public const int CZ_SYNC_POS = 0xE51; // Size: 26
		public const int ZC_ADVENTURE_BOOK_INFO = 0xE52; // Size: 0
		public const int CZ_DISCONNECT_REASON_FOR_LOG = 0xE53; // Size: 0
		public const int CZ_REQ_ADVENTURE_BOOK_RANK = 0xE54; // Size: 142
		public const int CZ_REQ_ADVENTURE_BOOK_REWARD = 0xE55; // Size: 74
		public const int CZ_REQ_GUILD_NEUTRALITY_ALARM = 0xE56; // Size: 14
		public const int CZ_REQ_QUEST_COMPLETE = 0xE57; // Size: 14
		public const int CZ_REQ_GUILD_ASSET_LOG = 0xE58; // Size: 10
		public const int ZC_COLONY_OCCUPATION_INFO = 0xE59; // Size: 0
		public const int ZC_BROAD_CAST_MY_INFO = 0xE5A; // Size: 30
		public const int CZ_REQ_RETURN_TO_CITY_FROM_COLONY_WAR = 0xE5B; // Size: 10
		public const int CZ_LOAD_COMPLETE = 0xE5C; // Size: 10
		public const int ZC_LOAD_COMPLETE = 0xE5D; // Size: 10
		public const int CZ_ACCEPT_CHALLENGE_MODE = 0xE5E; // Size: 14
		public const int CZ_ACCEPT_NEXT_LEVEL_CHALLENGE_MODE = 0xE5F; // Size: 14
		public const int CZ_ACCEPT_STOP_LEVEL_CHALLENGE_MODE = 0xE60; // Size: 14
		public const int ZC_UPDATE_CHALLENGE_MODE_WARP_PORTAL_MARK = 0xE61; // Size: 23
		public const int ZC_ATTENDANCE_RECEIPT_REWARD = 0xE62; // Size: 0
		public const int CZ_REGISTER_NEW_GUILD_EMBLEM = 0xE63; // Size: 20095
		public const int CZ_CHANGE_GUILD_EMBLEM = 0xE64; // Size: 20096
		public const int ZC_UPDATE_GUILD_EMBLEM = 0xE65; // Size: 24
		public const int CZ_REQUEST_CERTAIN_GUILD_EMBLEM = 0xE66; // Size: 20
		public const int ZC_RESPONSE_CERTAIN_GUILD_EMBLEM = 0xE67; // Size: 20040
		public const int CZ_REQUEST_GUILD_EMBLEM_INFO = 0xE68; // Size: 20
		public const int ZC_RESPONSE_GUILD_EMBLEM_INFO = 0xE69; // Size: 102
		public const int CZ_REQUEST_GUILD_INDEX = 0xE6A; // Size: 18
		public const int ZC_RESPONSE_GUILD_INDEX = 0xE6B; // Size: 24
		public const int CZ_REPORT_GUILDEMBLEM = 0xE6C; // Size: 74
		public const int ZC_DELETE_GUILD_EMBLEM = 0xE6D; // Size: 24
		public const int ZC_NXA_REQ_TICKET = 0xE6E; // Size: 10
		public const int CZ_NXA_TICKET = 0xE6F; // Size: 1034
		public const int CZ_NXA_REQ_BALANCE = 0xE70; // Size: 10
		public const int ZC_NXA_BALANCE = 0xE71; // Size: 40
		public const int CZ_NXA_REQ_ITEMLIST = 0xE72; // Size: 11
		public const int ZC_NXA_ITEMLIST = 0xE73; // Size: 0
		public const int CZ_NXA_REQ_PURCHASE = 0xE74; // Size: 15
		public const int ZC_NXA_PURCHASE = 0xE75; // Size: 1034
		public const int CZ_NXA_REQ_PICKUP_READY_ITEMS = 0xE76; // Size: 523
		public const int CZ_NXA_REQ_PURCHASE_CANCEL = 0xE77; // Size: 10
		public const int ZC_NXA_SELLITEMLIST = 0xE78; // Size: 0
		public const int CZ_REQ_PARTY_INFO = 0xE79; // Size: 10
		public const int CZ_REQ_RETURN_ORIGIN_SERVER = 0xE7A; // Size: 10
		public const int CZ_ANS_GIVEUP_PREV_PLAYING_INDUN = 0xE7B; // Size: 11
		public const int CZ_BADPLAYER_REPORT = 0xE7C; // Size: 146
		public const int ZC_ERROR_INFO = 0xE7D; // Size: 78
		public const int ZC_SEND_JSON_DUMP = 0xE7E; // Size: 0
		public const int CZ_SEND_JSON_DUMP = 0xE7F; // Size: 0

		private static readonly Dictionary<int, int> _sizes = new Dictionary<int, int>();
		private static readonly Dictionary<int, string> _names = new Dictionary<int, string>();

		static Op()
		{
			_sizes[CB_LOGIN] = 4457;
			_sizes[CB_LOGIN_BY_PASSPORT] = 1154;
			_sizes[CB_LOGOUT] = 10;
			_sizes[CB_START_BARRACK] = 11;
			_sizes[CB_COMMANDER_CREATE] = 93;
			_sizes[BC_COMMANDER_CREATE_SLOTID] = 11;
			_sizes[CB_COMMANDER_DESTROY] = 18;
			_sizes[CB_CHECK_CLIENT_INTEGRITY] = 74;
			_sizes[CB_CLIENT_INTEGRITY_FAIL] = 1035;
			_sizes[CB_START_GAME] = 13;
			_sizes[CB_BARRACKNAME_CHANGE] = 74;
			_sizes[CB_COMMANDER_MOVE] = 31;
			_sizes[CB_ECHO] = 30;
			_sizes[BC_LOGINOK] = 156;
			_sizes[BC_CYOU_LOGIN_FAIL] = 10;
			_sizes[BC_LOGIN_PACKET_RECEIVED] = 10;
			_sizes[BC_LOGOUTOK] = 10;
			_sizes[BC_COMMANDER_LIST] = 0;
			_sizes[BC_COMMANDER_CREATE] = 362;
			_sizes[BC_COMMANDER_DESTROY] = 11;
			_sizes[BC_START_GAMEOK] = 37;
			_sizes[BC_SINGLE_INFO] = 353;
			_sizes[BC_MESSAGE] = 0;
			_sizes[BC_ECHO] = 30;
			_sizes[BC_MYPAGE_MAP] = 0;
			_sizes[BC_BARRACKNAME_CHANGE] = 79;
			_sizes[CB_IES_MODIFY_INFO] = 0;
			_sizes[BC_IES_MODIFY_INFO] = 0;
			_sizes[BC_IES_MODIFY_LIST] = 0;
			_sizes[CB_IES_REVISION_DELETE] = 0;
			_sizes[BC_IES_REVISION_DELETE] = 0;
			_sizes[CB_SCREENSHOT_HASH] = 42;
			_sizes[CB_REQ_CHANNEL_TRAFFIC] = 14;
			_sizes[CB_VISIT] = 74;
			_sizes[CB_BUY_THEMA] = 22;
			_sizes[BC_ACCOUNT_PROP] = 0;
			_sizes[CB_CURRENT_BARRACK] = 39;
			_sizes[BC_NORMAL] = 0;
			_sizes[CB_POSE] = 15;
			_sizes[CB_PLACE_CMD] = 46;
			_sizes[CB_CHAT] = 0;
			_sizes[BC_CHAT] = 0;
			_sizes[CB_ECHO_NORMAL] = 0;
			_sizes[CB_REQ_SLOT_PRICE] = 10;
			_sizes[BC_REQ_SLOT_PRICE] = 14;
			_sizes[CB_CHANGE_BARRACK_LAYER] = 22;
			_sizes[CB_SELECT_BARRACK_LAYER] = 14;
			_sizes[CB_JUMP] = 19;
			_sizes[BC_JUMP] = 19;
			_sizes[BC_SERVER_ENTRY] = 22;
			_sizes[CB_PET_PC] = 26;
			_sizes[CB_PET_COMMAND] = 27;
			_sizes[CB_REQ_CHANGE_POSTBOX_STATE] = 23;
			_sizes[CB_REQ_GET_POSTBOX_ITEM] = 1051;
			_sizes[CB_REQ_POSTBOX_PAGE] = 14;
			_sizes[BC_WAIT_QUEUE_ORDER] = 14;
			_sizes[CB_CANCEL_SERVER_WAIT_QUEUE] = 10;
			_sizes[CB_NGS] = 0;
			_sizes[BC_NGS] = 0;
			_sizes[CB_GEMSCOOL_PCINFO] = 1290;
			_sizes[CB_NOT_AUTHORIZED_ADDON_LIST] = 1039;
			_sizes[CB_DEBUG_LOG_FILE] = 0;
			_sizes[ZC_TREASUREMARK_LIST_MAP] = 0;
			_sizes[CS_LOGIN] = 91;
			_sizes[SC_NORMAL] = 0;
			_sizes[SC_FROM_INTEGRATE] = 0;
			_sizes[CS_REGISTER_SNS_ID] = 24;
			_sizes[CS_REQ_SNS_PC_INFO] = 0;
			_sizes[CS_REQ_ADD_FRIEND] = 74;
			_sizes[CS_REQ_BLOCK_FRIEND] = 74;
			_sizes[CS_FRIEND_CMD] = 32;
			_sizes[CS_FRIEND_SET_ADDINFO] = 168;
			_sizes[CS_CHAT] = 0;
			_sizes[CS_GROUP_CHAT_INVITE] = 114;
			_sizes[CS_GROUP_CHAT_INVITE_BY_TAG] = 26;
			_sizes[CS_ALLOW_GROUP_CHAT_TAG_INVITE] = 50;
			_sizes[CS_REFRESH_GROUP_CHAT] = 10;
			_sizes[CS_CREATE_GROUP_CHAT] = 10;
			_sizes[CS_REQ_CHAT_HISTORY] = 26;
			_sizes[CS_REQ_OUT_ROOM] = 18;
			_sizes[CS_REQ_RELATED_PC_SESSION] = 24;
			_sizes[CS_REDIS_SKILLPOINT] = 26;
			_sizes[CS_PARTY_CLIENT_INFO_SEND] = 0;
			_sizes[CS_NORMAL_GAME_START] = 10;
			_sizes[CS_REQUEST_PVP_RANKING] = 92;
			_sizes[CS_REQUEST_ALL_SEASON_TOP_PVP_RANKING] = 84;
			_sizes[CS_INVITE_PARTY_PVP] = 14;
			_sizes[CS_ACCEPT_PARTY_PVP] = 23;
			_sizes[CS_LIKE_IT] = 96;
			_sizes[CS_UNLIKE_IT] = 32;
			_sizes[CS_LIKE_IT_CONFIRM] = 24;
			_sizes[CS_ADD_RELATION_SCORE] = 96;
			_sizes[CS_GET_LIKE_COUNT] = 24;
			_sizes[CZ_CONNECT] = 1239;
			_sizes[ZC_CONNECT_OK] = 0;
			_sizes[ZC_MOVE_ZONE] = 11;
			_sizes[CZ_MOVE_ZONE_OK] = 10;
			_sizes[ZC_CONNECT_FAILED] = 0;
			_sizes[CZ_GAME_READY] = 10;
			_sizes[ZC_MOVE_ZONE_OK] = 61;
			_sizes[CZ_LOGOUT] = 11;
			_sizes[CZ_MOVE_BARRACK] = 11;
			_sizes[ZC_MOVE_BARRACK] = 10;
			_sizes[ZC_LOGOUT_OK] = 10;
			_sizes[ZC_MESSAGE] = 0;
			_sizes[ZC_RESET_VIEW] = 10;
			_sizes[ZC_START_GAME] = 30;
			_sizes[ZC_QUIET] = 11;
			_sizes[ZC_ENTER_PC] = 366;
			_sizes[ZC_ENTER_MONSTER] = 0;
			_sizes[ZC_ENTER_DUMMYPC] = 328;
			_sizes[ZC_UPDATED_DUMMYPC] = 286;
			_sizes[ZC_ENTER_ITEM] = 107;
			_sizes[ZC_LEAVE] = 16;
			_sizes[ZC_MOVE_PATH] = 46;
			_sizes[ZC_MOVE_POS] = 47;
			_sizes[ZC_MOVE_BEZIER] = 79;
			_sizes[ZC_MOVE_DIR] = 44;
			_sizes[ZC_EXPECTED_STOPPOS] = 39;
			_sizes[ZC_MSPD] = 18;
			_sizes[ZC_MOVE_SPEED] = 23;
			_sizes[ZC_MOVE_STOP] = 27;
			_sizes[ZC_REST_SIT] = 16;
			_sizes[ZC_JUMP] = 23;
			_sizes[ZC_JUMP_DIR] = 38;
			_sizes[ZC_ORDER_SKILL_JUMP] = 14;
			_sizes[ZC_SKILL_JUMP] = 42;
			_sizes[ZC_SET_POS] = 27;
			_sizes[ZC_FILE_MOVE] = 50;
			_sizes[CZ_LEAVE_TO_DUNGEON] = 10;
			_sizes[ZC_UPDATED_PCAPPEARANCE] = 286;
			_sizes[ZC_UPDATED_MONSTERAPPEARANCE] = 0;
			_sizes[ZC_CHAT] = 0;
			_sizes[ZC_CHAT_WITH_TEXTCODE] = 18;
			_sizes[ZC_STANCE_CHANGE] = 18;
			_sizes[ZC_ADD_HP] = 26;
			_sizes[ZC_SKILL_CAST_CANCEL] = 14;
			_sizes[ZC_SKILL_CAST] = 42;
			_sizes[ZC_SKILL_READY] = 54;
			_sizes[ZC_SKILL_DISABLE] = 19;
			_sizes[ZC_SKILL_USE_CANCEL] = 14;
			_sizes[ZC_SKILL_MELEE_TARGET] = 0;
			_sizes[ZC_SKILL_MELEE_GROUND] = 0;
			_sizes[ZC_SKILL_FORCE_TARGET] = 0;
			_sizes[ZC_SKILL_FORCE_GROUND] = 0;
			_sizes[ZC_SKILL_HIT_INFO] = 0;
			_sizes[ZC_BUFF_LIST] = 0;
			_sizes[ZC_BUFF_ADD] = 0;
			_sizes[ZC_BUFF_UPDATE] = 0;
			_sizes[ZC_BUFF_REMOVE] = 24;
			_sizes[ZC_BUFF_CLEAR] = 15;
			_sizes[CZ_BUFF_REMOVE] = 14;
			_sizes[CZ_INTE_WARP] = 14;
			_sizes[ZC_ROTATE] = 24;
			_sizes[ZC_ROTATE_RESERVED] = 22;
			_sizes[ZC_HEAD_ROTATE] = 22;
			_sizes[ZC_TARGET_ROTATE] = 22;
			_sizes[ZC_QUICK_ROTATE] = 22;
			_sizes[ZC_POSE] = 38;
			_sizes[ZC_DEAD] = 0;
			_sizes[ZC_RESURRECT] = 22;
			_sizes[ZC_CHANGE_RELATION] = 15;
			_sizes[ZC_RESURRECT_DIALOG] = 14;
			_sizes[ZC_HIT_INFO] = 69;
			_sizes[ZC_HEAL_INFO] = 34;
			_sizes[ZC_CAUTION_DAMAGE_INFO] = 19;
			_sizes[ZC_CAUTION_DAMAGE_RELEASE] = 14;
			_sizes[ZC_KNOCKBACK_INFO] = 74;
			_sizes[ZC_KNOCKDOWN_INFO] = 75;
			_sizes[CZ_RESURRECT] = 19;
			_sizes[ZC_RESURRECT_SAVE_POINT_ACK] = 11;
			_sizes[ZC_RESURRECT_HERE_ACK] = 11;
			_sizes[CZ_CLICK_TRIGGER] = 15;
			_sizes[CZ_KEYBOARD_MOVE] = 41;
			_sizes[CZ_EXPECTED_STOP_POS] = 31;
			_sizes[CZ_JUMP] = 11;
			_sizes[CZ_DASHRUN] = 12;
			_sizes[CZ_SKILL_JUMP_REQ] = 30;
			_sizes[CZ_MOVE_PATH] = 27;
			_sizes[CZ_MOVE_STOP] = 35;
			_sizes[CZ_REST_SIT] = 10;
			_sizes[CZ_REQ_CHAR_SLOT] = 11;
			_sizes[CZ_ON_AIR] = 10;
			_sizes[CZ_ON_GROUND] = 10;
			_sizes[CZ_MOVEMENT_INFO] = 23;
			_sizes[CZ_SKILL_TARGET] = 19;
			_sizes[CZ_SKILL_TARGET_ANI] = 23;
			_sizes[CZ_SKILL_GROUND] = 61;
			_sizes[CZ_SKILL_SELF] = 35;
			_sizes[CZ_SKILL_CANCEL] = 12;
			_sizes[CZ_HOLD] = 11;
			_sizes[CZ_ROTATE] = 18;
			_sizes[CZ_HEAD_ROTATE] = 18;
			_sizes[CZ_TARGET_ROTATE] = 18;
			_sizes[CZ_POSE] = 34;
			_sizes[CZ_CHAT] = 0;
			_sizes[CZ_SELF_CHAT] = 0;
			_sizes[CZ_CHAT_LOG] = 0;
			_sizes[CZ_SHOUT] = 0;
			_sizes[CZ_ITEM_DROP] = 22;
			_sizes[CZ_ITEM_DELETE] = 0;
			_sizes[CZ_ITEM_USE] = 22;
			_sizes[CZ_ITEM_USE_TO_ITEM] = 30;
			_sizes[CZ_ITEM_USE_TO_GROUND] = 30;
			_sizes[CZ_ITEM_BUY] = 0;
			_sizes[CZ_ITEM_SELL] = 0;
			_sizes[CZ_ITEM_EQUIP] = 19;
			_sizes[CZ_ITEM_UNEQUIP] = 11;
			_sizes[CZ_REQ_DELETE_EXPIRED_ITEMS] = 18;
			_sizes[ZC_CHECK_INVINDEX] = 34;
			_sizes[CZ_PREMIUM_ENCHANTCHIP] = 26;
			_sizes[CZ_PREMIUM_GACHACUBE] = 10;
			_sizes[ZC_ITEM_INVENTORY_LIST] = 0;
			_sizes[ZC_ITEM_INVENTORY_DIVISION_LIST] = 0;
			_sizes[ZC_ITEM_INVENTORY_INDEX_LIST] = 0;
			_sizes[ZC_ITEM_EQUIP_LIST] = 0;
			_sizes[ZC_ITEM_ADD] = 0;
			_sizes[ZC_ITEM_REMOVE] = 24;
			_sizes[ZC_ITEM_USE] = 18;
			_sizes[ZC_ITEM_USE_TO_GROUND] = 26;
			_sizes[ZC_QUICK_SLOT_LIST] = 0;
			_sizes[ZC_SKILL_LIST] = 0;
			_sizes[ZC_SKILL_ADD] = 0;
			_sizes[ZC_ABILITY_LIST] = 0;
			_sizes[CZ_REQ_OPEN_ITEM_DUNGEON] = 19;
			_sizes[CZ_ANSWER_OPEN_ITEM_DUNGEON] = 19;
			_sizes[CZ_SEND_ITEM_PROP_TO_ALCHMIST] = 28;
			_sizes[CZ_EXCUTE_ITEM_DUNGEON] = 34;
			_sizes[ZC_RECIVE_ITEM_PROP_TO_TARGET] = 0;
			_sizes[CZ_DISPEL_DEBUFF_TOGGLE] = 14;
			_sizes[CZ_JUNGTAN_TOGGLE] = 24;
			_sizes[ZC_EXP_UP] = 26;
			_sizes[ZC_EXP_UP_BY_MONSTER] = 30;
			_sizes[ZC_PC_LEVELUP] = 18;
			_sizes[ZC_PC_STAT_AVG] = 34;
			_sizes[ZC_MAX_EXP_CHANGED] = 38;
			_sizes[ZC_TEXT] = 0;
			_sizes[ZC_UPDATE_SP] = 19;
			_sizes[ZC_RESTORATION] = 16;
			_sizes[ZC_UPDATE_MHP] = 18;
			_sizes[CZ_DIALOG_ACK] = 14;
			_sizes[CZ_DIALOG_SELECT] = 11;
			_sizes[CZ_DIALOG_STRINGINPUT] = 138;
			_sizes[ZC_DIALOG_OK] = 0;
			_sizes[ZC_DIALOG_NEXT] = 0;
			_sizes[ZC_DIALOG_SELECT] = 0;
			_sizes[ZC_DIALOG_ITEM_SELECT] = 0;
			_sizes[ZC_DIALOG_CLOSE] = 10;
			_sizes[ZC_DIALOG_TRADE] = 43;
			_sizes[ZC_DIALOG_COMMON_TRADE] = 43;
			_sizes[ZC_DIALOG_NUMBERRANGE] = 0;
			_sizes[ZC_DIALOG_STRINGINPUT] = 0;
			_sizes[ZC_ADDON_MSG] = 0;
			_sizes[CZ_UI_EVENT] = 0;
			_sizes[ZC_PLAY_SOUND] = 19;
			_sizes[ZC_STOP_SOUND] = 18;
			_sizes[ZC_PLAY_MUSICQUEUE] = 18;
			_sizes[ZC_STOP_MUSICQUEUE] = 18;
			_sizes[ZC_PLAY_ANI] = 28;
			_sizes[ZC_PLAY_ANI_SELFISH] = 23;
			_sizes[ZC_CHANGE_ANI] = 48;
			_sizes[CZ_MOVE_CAMP] = 18;
			_sizes[CZ_CAMPINFO] = 18;
			_sizes[ZC_CAMPINFO] = 22;
			_sizes[ZC_FIX_ANIM] = 18;
			_sizes[CZ_TARGET_JOB_INFO] = 18;
			_sizes[ZC_TARGET_JOB_INFO] = 18;
			_sizes[ZC_MOVE_ANIM] = 16;
			_sizes[ZC_STD_ANIM] = 15;
			_sizes[ZC_PLAY_ALARMSOUND] = 87;
			_sizes[ZC_STOP_ALARMSOUND] = 14;
			_sizes[ZC_PLAY_EXP_TEXT] = 18;
			_sizes[ZC_PLAY_NAVI_EFFECT] = 154;
			_sizes[ZC_UPDATE_ALL_STATUS] = 30;
			_sizes[ZC_OBJECT_PROPERTY] = 0;
			_sizes[ZC_DUMP_PROPERTY] = 0;
			_sizes[ZC_SHOUT] = 0;
			_sizes[ZC_SHOUT_FAILED] = 11;
			_sizes[CZ_EXCHANGE_REQUEST] = 14;
			_sizes[ZC_EXCHANGE_REQUEST_ACK] = 76;
			_sizes[ZC_EXCHANGE_REQUEST_RECEIVED] = 75;
			_sizes[CZ_EXCHANGE_ACCEPT] = 10;
			_sizes[CZ_EXCHANGE_DECLINE] = 10;
			_sizes[ZC_EXCHANGE_DECLINE_ACK] = 10;
			_sizes[ZC_EXCHANGE_START] = 76;
			_sizes[CZ_EXCHANGE_OFFER] = 30;
			_sizes[ZC_EXCHANGE_OFFER_ACK] = 0;
			_sizes[CZ_EXCHANGE_AGREE] = 10;
			_sizes[ZC_EXCHANGE_AGREE_ACK] = 11;
			_sizes[CZ_EXCHANGE_FINALAGREE] = 10;
			_sizes[ZC_EXCHANGE_FINALAGREE_ACK] = 11;
			_sizes[CZ_EXCHANGE_CANCEL] = 10;
			_sizes[ZC_EXCHANGE_CANCEL_ACK] = 10;
			_sizes[ZC_EXCHANGE_SUCCESS] = 10;
			_sizes[ZC_COOLDOWN_LIST] = 0;
			_sizes[ZC_COOLDOWN_CHANGED] = 31;
			_sizes[ZC_OVERHEAT_CHANGED] = 34;
			_sizes[ZC_TEST_AGENT] = 22;
			_sizes[CZ_COMMON_SHOP_LIST] = 10;
			_sizes[ZC_COMMON_SHOP_LIST] = 12;
			_sizes[ZC_TIME_FACTOR] = 14;
			_sizes[ZC_PARTY_ENTER] = 0;
			_sizes[ZC_PARTY_OUT] = 28;
			_sizes[ZC_PARTY_DESTROY] = 19;
			_sizes[ZC_PARTY_INFO] = 0;
			_sizes[ZC_PARTY_LIST] = 0;
			_sizes[ZC_PARTY_CHAT] = 0;
			_sizes[ZC_PARTY_INST_INFO] = 0;
			_sizes[ZC_CHANGE_EQUIP_DURABILITY] = 15;
			_sizes[CZ_DIALOG_TX] = 0;
			_sizes[CZ_REQ_RECIPE] = 0;
			_sizes[ZC_CUSTOM_DIALOG] = 79;
			_sizes[ZC_SESSION_OBJECTS] = 0;
			_sizes[ZC_SESSION_OBJ_ADD] = 0;
			_sizes[ZC_SESSION_OBJ_REMOVE] = 14;
			_sizes[ZC_SESSION_OBJ_TIME] = 18;
			_sizes[CZ_S_OBJ_VALUE_C] = 26;
			_sizes[CZ_REQ_NORMAL_TX] = 45;
			_sizes[ZC_COMMANDER_LOADER_INFO] = 0;
			_sizes[ZC_MOVE_SINGLE_ZONE] = 22;
			_sizes[ZC_BACKTO_ORIGINAL_SERVER] = 12;
			_sizes[CZ_BACKTO_ORIGINAL_SERVER] = 12;
			_sizes[CZ_REQ_NORMAL_TX_NUMARG] = 0;
			_sizes[ZC_UI_OPEN] = 43;
			_sizes[ZC_ENABLE_CONTROL] = 79;
			_sizes[ZC_CHANGE_CAMERA] = 35;
			_sizes[ZC_MONSTER_SDR_CHANGED] = 15;
			_sizes[ZC_MOVE_IGNORE_COLLISION] = 34;
			_sizes[ZC_CHANGE_CAMERA_ZOOM] = 38;
			_sizes[ZC_PLAY_SKILL_ANI] = 86;
			_sizes[ZC_PLAY_SKILL_CAST_ANI] = 34;
			_sizes[CZ_REQ_ITEM_GET] = 14;
			_sizes[ZC_ITEM_GET] = 22;
			_sizes[CZ_GUARD] = 19;
			_sizes[ZC_GUARD] = 23;
			_sizes[ZC_STAMINA] = 14;
			_sizes[ZC_ADD_STAMINA] = 14;
			_sizes[ZC_GM_ORDER] = 14;
			_sizes[ZC_MYPC_ENTER] = 23;
			_sizes[ZC_LOCK_KEY] = 79;
			_sizes[ZC_SAVE_INFO] = 10;
			_sizes[CZ_SAVE_INFO] = 0;
			_sizes[ZC_OPTION_LIST] = 0;
			_sizes[ZC_SKILLMAP_LIST] = 0;
			_sizes[CZ_GIVEITEM_TO_DUMMYPC] = 22;
			_sizes[CZ_FOOD_TABLE_TITLE] = 79;
			_sizes[CZ_USE_TP_AND_ENTER_INDUN] = 522;
			_sizes[CZ_USE_RANKRESET_ITEM] = 18;
			_sizes[CZ_REQ_RANKRESET_SYSTEM] = 19;
			_sizes[ZC_SET_LAYER] = 15;
			_sizes[ZC_CREATE_LAYERBOX] = 42;
			_sizes[ZC_RESET_BOX] = 15;
			_sizes[ZC_CREATE_SCROLLLOCKBOX] = 42;
			_sizes[ZC_REMOVE_SCROLLLOCKBOX] = 14;
			_sizes[CZ_DYNAMIC_CASTING_START] = 25;
			_sizes[CZ_DYNAMIC_CASTING_END] = 20;
			_sizes[CZ_SKILL_CANCEL_SCRIPT] = 10;
			_sizes[ZC_LEAVE_TRIGGER] = 10;
			_sizes[ZC_BORN] = 14;
			_sizes[ZC_ACHIEVE_POINT_LIST] = 0;
			_sizes[ZC_ACHIEVE_POINT] = 22;
			_sizes[CZ_ACHIEVE_EQUIP] = 14;
			_sizes[ZC_ACHIEVE_EQUIP] = 22;
			_sizes[CZ_ACHIEVE_REWARD] = 14;
			_sizes[CZ_CHANGE_CONFIG] = 18;
			_sizes[CZ_CHANGE_CONFIG_STR] = 34;
			_sizes[ZC_WORLD_MSG] = 47;
			_sizes[ZC_ENABLE_SHOW_ITEM_GET] = 12;
			_sizes[ZC_LOGIN_TIME] = 18;
			_sizes[ZC_GIVE_EXP_TO_PC] = 50;
			_sizes[ZC_LAYER_PC_LIST] = 0;
			_sizes[ZC_LAYER_PC_SOBJ_PROP] = 0;
			_sizes[CZ_CUSTOM_COMMAND] = 26;
			_sizes[ZC_LAYER_INFO] = 14;
			_sizes[CZ_CHAT_MACRO] = 146;
			_sizes[ZC_CHAT_MACRO_LIST] = 0;
			_sizes[ZC_RULLET_LIST] = 0;
			_sizes[ZC_QUICKSLOT_REGISTER] = 50;
			_sizes[CZ_QUICKSLOT_LIST] = 0;
			_sizes[CZ_DOUBLE_ITEM_EQUIP] = 28;
			_sizes[ZC_TRICK_PACKET] = 0;
			_sizes[ZC_COOLDOWN_RATE] = 26;
			_sizes[ZC_MAP_REVEAL_LIST] = 0;
			_sizes[CZ_MAP_REVEAL_INFO] = 146;
			_sizes[CZ_MAP_SEARCH_INFO] = 55;
			_sizes[ZC_EXEC_CLIENT_SCP] = 0;
			_sizes[ZC_SET_NPC_STATE] = 22;
			_sizes[ZC_NPC_STATE_LIST] = 0;
			_sizes[CZ_QUEST_NPC_STATE_CHECK] = 14;
			_sizes[ZC_RANK_ACHIEVE_ADD] = 18;
			_sizes[CZ_IES_MODIFY_INFO] = 0;
			_sizes[ZC_IES_MODIFY_INFO] = 0;
			_sizes[ZC_IES_MODIFY_LIST] = 0;
			_sizes[CZ_IES_REVISION_DELETE] = 0;
			_sizes[ZC_IES_REVISION_DELETE] = 0;
			_sizes[ZC_EQUIP_ITEM_REMOVE] = 22;
			_sizes[ZC_SOLD_ITEM_LIST] = 0;
			_sizes[ZC_SOLD_ITEM_DIVISION_LIST] = 0;
			_sizes[CZ_SOLD_ITEM] = 19;
			_sizes[CZ_WAREHOUSE_CMD] = 32;
			_sizes[CZ_SWAP_ETC_INV_CHANGE_INDEX] = 35;
			_sizes[CZ_SORT_INV] = 12;
			_sizes[CZ_EXTEND_WAREHOUSE] = 11;
			_sizes[CZ_CAST_CONTROL_SHOT] = 10;
			_sizes[ZC_PC_PROP_UPDATE] = 15;
			_sizes[CZ_CLIENT_DAMAGE] = 14;
			_sizes[CZ_CLIENT_ATTACK] = 15;
			_sizes[ZC_SYSTEM_MSG] = 0;
			_sizes[ZC_FSM_MOVE] = 0;
			_sizes[CZ_QUEST_CHECK_SAVE] = 50;
			_sizes[CZ_SPRAY_REQ_INFO] = 14;
			_sizes[CZ_SPRAY_DRAW_INFO] = 0;
			_sizes[ZC_SPRAY_ID] = 22;
			_sizes[ZC_SPRAY_DRAW_INFO] = 0;
			_sizes[ZC_MONSTER_LIFETIME] = 18;
			_sizes[ZC_SPRAY_LIKE_LIST] = 0;
			_sizes[ZC_SHARED_MSG] = 14;
			_sizes[CZ_REQ_TX_ITEM] = 0;
			_sizes[ZC_TEST_DBG] = 0;
			_sizes[ZC_MONSTER_DIST] = 0;
			_sizes[ZC_RESET_SKILL_FORCEID] = 14;
			_sizes[ZC_EMOTICON] = 22;
			_sizes[ZC_SHOW_EMOTICON] = 22;
			_sizes[ZC_TREASUREMARK_BY_MAP] = 0;
			_sizes[ZC_SHOW_MAP] = 0;
			_sizes[CZ_FLEE_OBSTACLE] = 26;
			_sizes[ZC_HOLD_MOVE_PATH] = 15;
			_sizes[ZC_ENTER_HOOK] = 14;
			_sizes[ZC_LEAVE_HOOK] = 14;
			_sizes[ZC_MONSTER_PROPERTY] = 0;
			_sizes[ZC_GROUND_EFFECT] = 54;
			_sizes[ZC_FLY] = 22;
			_sizes[ZC_FLY_OPTION] = 18;
			_sizes[ZC_FLY_MATH] = 27;
			_sizes[ZC_FLY_HEIGHT] = 18;
			_sizes[ZC_UPDATE_SHIELD] = 18;
			_sizes[ZC_SHOW_MODEL] = 19;
			_sizes[ZC_SKILL_RANGE_DBG] = 62;
			_sizes[ZC_SKILL_RANGE_FAN] = 44;
			_sizes[ZC_SKILL_RANGE_SQUARE] = 44;
			_sizes[ZC_SKILL_RANGE_CIRCLE] = 32;
			_sizes[ZC_SKILL_RANGE_DONUTS] = 36;
			_sizes[ZC_TEAMID] = 15;
			_sizes[ZC_PC] = 0;
			_sizes[CZ_LOG] = 0;
			_sizes[ZC_MOTIONBLUR] = 15;
			_sizes[ZC_PLAY_FORCE] = 82;
			_sizes[ZC_CAST_TARGET] = 18;
			_sizes[ZC_START_INFO] = 0;
			_sizes[ZC_JOB_EXP_UP] = 26;
			_sizes[ZC_JOB_PTS] = 22;
			_sizes[ZC_MON_STAMINA] = 26;
			_sizes[CZ_CUSTOM_SCP] = 14;
			_sizes[ZC_VIEW_FOCUS] = 28;
			_sizes[ZC_HARDCODED_SKILL] = 30;
			_sizes[CZ_HARDCODED_SKILL] = 34;
			_sizes[ZC_FORCE_MOVE] = 34;
			_sizes[ZC_HSKILL_CONTROL] = 26;
			_sizes[ZC_CANCEL_DEADEVENT] = 14;
			_sizes[ZC_ACTION_PKS] = 39;
			_sizes[CZ_HARDCODED_ITEM] = 22;
			_sizes[CZ_CANCEL_TRANSFORM_SKILL] = 10;
			_sizes[CZ_BRIQUET] = 32;
			_sizes[ZC_VIBRATE] = 34;
			_sizes[ZC_COUNTER_MOVE] = 14;
			_sizes[CZ_COUNTER_ATTACK] = 14;
			_sizes[CZ_CLIENT_DIRECT] = 30;
			_sizes[ZC_CLIENT_DIRECT] = 34;
			_sizes[ZC_OWNER] = 18;
			_sizes[ZC_GD_RANK] = 14;
			_sizes[CZ_RUN_BGEVENT] = 74;
			_sizes[ZC_ADD_SKILL_EFFECT] = 22;
			_sizes[ZC_ITEM_DROPABLE] = 14;
			_sizes[CZ_ITEM_DROP_TO_OBJECT] = 26;
			_sizes[ZC_NORMAL] = 0;
			_sizes[CZ_G_QUEST_CHECK] = 14;
			_sizes[ZC_MOVE_PATH_MATH] = 34;
			_sizes[CZ_MYPAGE_COMMENT_ADD] = 278;
			_sizes[CZ_MYPAGE_COMMENT_DELETE] = 18;
			_sizes[CZ_GUESTPAGE_COMMENT_ADD] = 278;
			_sizes[CZ_GET_TARGET_MYPAGE] = 14;
			_sizes[CZ_ON_MYPAGE_MODE] = 14;
			_sizes[CZ_RESET_SOCIAL_MODE] = 10;
			_sizes[CZ_GET_TARGET_GUESTPAGE] = 14;
			_sizes[CZ_ADD_SELLMODE_ITEM] = 30;
			_sizes[CZ_DELETE_SELLMODE_ITEM] = 18;
			_sizes[CZ_ON_SELLITEM_MODE] = 14;
			_sizes[ZC_MYPAGE_MAP] = 0;
			_sizes[ZC_GUESTPAGE_MAP] = 0;
			_sizes[ZC_ON_MYPAGE_MODE] = 0;
			_sizes[ZC_RESET_SOCIAL_MODE] = 14;
			_sizes[CZ_ON_ITEMBUY_MODE] = 0;
			_sizes[ZC_ON_BUYITEM_MODE] = 0;
			_sizes[ZC_SHOW_GROUND_ITEM_MARK] = 34;
			_sizes[ZC_HELP_LIST] = 0;
			_sizes[ZC_HELP_ADD] = 15;
			_sizes[CZ_CLIENT_HIT_LIST] = 0;
			_sizes[ZC_PC_ATKSTATE] = 15;
			_sizes[ZC_SEND_PREMIUM_STATE] = 20;
			_sizes[CZ_HELP_READ_TYPE] = 18;
			_sizes[CZ_MOVE_PATH_END] = 10;
			_sizes[ZC_COLL_DAMAGE] = 15;
			_sizes[CZ_KEYBOARD_BEAT] = 10;
			_sizes[CZ_MOVEHIT_SCP] = 22;
			_sizes[ZC_SYNC_START] = 18;
			_sizes[ZC_SYNC_END] = 18;
			_sizes[ZC_SYNC_EXEC] = 14;
			_sizes[ZC_SYNC_EXEC_BY_SKILL_TIME] = 22;
			_sizes[CZ_STOP_TIMEACTION] = 11;
			_sizes[CZ_REQ_DUMMYPC_INFO] = 18;
			_sizes[CZ_VISIT_BARRACK] = 74;
			_sizes[CZ_SPC_SKILL_POS] = 22;
			_sizes[CZ_CHANGE_HEAD] = 74;
			_sizes[CZ_CREATE_ARROW_CRAFT] = 14;
			_sizes[CZ_EXCHANGE_ANTIQUE] = 22;
			_sizes[CZ_REQ_MINITEXT] = 266;
			_sizes[ZC_PC_MOVE_STOP] = 39;
			_sizes[CZ_STOP_ALLPC] = 10;
			_sizes[CZ_COMPLETE_PRELOAD] = 14;
			_sizes[CZ_MGAME_JOIN_CMD] = 46;
			_sizes[CZ_ADD_HELP] = 14;
			_sizes[ZC_ATTACH_TO_OBJ] = 53;
			_sizes[ZC_DETACH_FROM_OBJ] = 18;
			_sizes[ZC_RUN_FROM] = 18;
			_sizes[ZC_LOOKAT_OBJ] = 18;
			_sizes[CZ_SKILL_CELL_LIST] = 0;
			_sizes[CZ_SKILL_TOOL_GROUND_POS] = 26;
			_sizes[CZ_DIRECTION_PROCESS] = 18;
			_sizes[CZ_DIRECTION_MOVE_STATE] = 0;
			_sizes[ZC_TO_ALL_CLIENT] = 0;
			_sizes[ZC_TO_CLIENT] = 0;
			_sizes[CZ_REWARD_CMD] = 14;
			_sizes[CZ_PROPERTY_COMPARE] = 16;
			_sizes[ZC_PROPERTY_COMPARE] = 0;
			_sizes[ZC_PROPERTY_COMPARE_FOR_ACT] = 0;
			_sizes[ZC_FACTION] = 18;
			_sizes[ZC_SEND_CASH_VALUE] = 0;
			_sizes[ZC_BEGIN_KILL_LOG] = 10;
			_sizes[ZC_END_KILL_LOG] = 10;
			_sizes[ZC_CLEAR_KILL_LOG] = 10;
			_sizes[CZ_NPC_AUCTION_CMD] = 30;
			_sizes[ZC_DIRECTION_APC] = 30;
			_sizes[ZC_BGMODEL_ANIM_INFO] = 19;
			_sizes[ZC_ATTACH_BY_KNOCKBACK] = 42;
			_sizes[CZ_OBJECT_MOVE] = 30;
			_sizes[CZ_CONTROL_OBJECT_ROTATE] = 22;
			_sizes[CZ_SUMMON_COMMAND] = 18;
			_sizes[CZ_VEHICLE_RIDE] = 15;
			_sizes[CZ_REQ_ACHIEVE_RANK_PAGE_INFO] = 78;
			_sizes[ZC_SPC_TRIGGER_EXEC] = 34;
			_sizes[CZ_REQ_MGAME_VIEW] = 18;
			_sizes[CZ_REQ_MGAME_CHAT] = 0;
			_sizes[CZ_TOURNAMENT_GIFT] = 18;
			_sizes[CZ_PARTY_INVITE_ACCEPT] = 87;
			_sizes[CZ_PARTY_INVITE_CANCEL] = 91;
			_sizes[CZ_PARTY_PROP_CHANGE] = 147;
			_sizes[CZ_REQ_MARKET_REGISTER] = 40;
			_sizes[CZ_REQ_MARKET_MINMAX_INFO] = 18;
			_sizes[CZ_REQ_MARKET_BUY] = 0;
			_sizes[CZ_REQ_MARKET_LIST] = 138;
			_sizes[CZ_REQ_MY_SELL_LIST] = 14;
			_sizes[CZ_REQ_CABINET_LIST] = 10;
			_sizes[CZ_REQ_GET_CABINET_ITEM] = 26;
			_sizes[CZ_REQ_CANCEL_MARKET_ITEM] = 18;
			_sizes[CZ_INV_ITEM_LOCK] = 19;
			_sizes[CZ_OBJ_RECORD_POS] = 0;
			_sizes[CZ_FORMATION_CMD] = 32;
			_sizes[CZ_REGISTER_AUTOSELLER] = 0;
			_sizes[CZ_OPEN_AUTOSELLER] = 66;
			_sizes[CZ_BUY_AUTOSELLER_ITEMS] = 0;
			_sizes[CZ_SELL_MY_AUTOSELLER_ITEMS] = 0;
			_sizes[CZ_PUZZLE_CRAFT] = 0;
			_sizes[CZ_PET_EQUIP] = 34;
			_sizes[CZ_PET_AUTO_ATK] = 11;
			_sizes[ZC_PET_AUTO_ATK] = 11;
			_sizes[ZC_FOUND_PARTY_LIST] = 0;
			_sizes[ZC_NEAR_PARTY_LIST] = 0;
			_sizes[ZC_RECOMMEND_PARTY_INFO] = 0;
			_sizes[CZ_REQUEST_SOME_PARTY] = 90;
			_sizes[CZ_REFRESH_MEMBERRECOMMEND_LIST] = 10;
			_sizes[ZC_TO_SOMEWHERE_CLIENT] = 0;
			_sizes[CZ_REVEAL_NPC_STATE] = 14;
			_sizes[CZ_CHANGE_CHANNEL] = 12;
			_sizes[CZ_REQ_CHANNEL_TRAFFICS] = 12;
			_sizes[CZ_BUY_PROPERTYSHOP_ITEM] = 0;
			_sizes[CZ_SKILL_USE_HEIGHT] = 14;
			_sizes[CZ_CHANGE_GUILD_NEUTRALITY] = 10;
			_sizes[CZ_SAVE_GUILD_BOARD] = 110;
			_sizes[CZ_DELETE_PARTY_EVENT] = 20;
			_sizes[CZ_PING] = 10;
			_sizes[ZC_PING] = 10;
			_sizes[CZ_REQ_REMAIN_NEXONCASH] = 10;
			_sizes[CZ_REQ_OPEN_INGAMESHOP_UI] = 10;
			_sizes[CZ_REQ_BUY_INGAMESHOP_ITEM] = 78;
			_sizes[CZ_REQ_BUY_ALL_INGAMESHOP_ITEM] = 10;
			_sizes[CZ_REQ_PICKUP_CASHITEM] = 37;
			_sizes[CZ_REQ_REFUND_CASHITEM] = 33;
			_sizes[ZC_XIGNCODE_BUFFER] = 524;
			_sizes[CZ_XIGNCODE_BUFFER] = 524;
			_sizes[CZ_SYSTEM_LOG_SAVE_TO_MONGODB] = 280;
			_sizes[CZ_CHANGE_TITLE] = 74;
			_sizes[CZ_PC_COMMENT_CHANGE] = 0;
			_sizes[CZ_AUTTOSELLER_BUYER_CLOSE] = 18;
			_sizes[CZ_REQ_ITEM_LIST] = 11;
			_sizes[CZ_REQ_ACC_WARE_VIS_LOG] = 10;
			_sizes[CZ_HIT_MISSILE] = 14;
			_sizes[CZ_I_NEED_PARTY] = 23;
			_sizes[CZ_PARTY_JOIN_BY_LINK] = 19;
			_sizes[ZC_RECOMMEND_PARTYMEMBER_INFO] = 0;
			_sizes[CZ_PVP_ZONE_CMD] = 26;
			_sizes[CZ_PVP_CHAT] = 0;
			_sizes[CZ_CARDBATTLE_CMD] = 26;
			_sizes[CZ_REQ_UPDATE_CONTENTS_SESSION] = 10;
			_sizes[CZ_REQ_FRIENDLY_FIGHT] = 15;
			_sizes[CZ_HARDSKILL_POS_LIST] = 0;
			_sizes[CZ_CART_POSITION] = 26;
			_sizes[CZ_REQ_RIDE_CART] = 18;
			_sizes[CZ_DUMMYPC_SKILL_POS] = 26;
			_sizes[CZ_NGS] = 0;
			_sizes[ZC_NGS] = 0;
			_sizes[CZ_PARTY_MEMBER_SKILL_USE] = 0;
			_sizes[CZ_PARTY_MEMBER_SKILL_ACCEPT] = 23;
			_sizes[CZ_SYSTEM_LOG_TO_SERVER] = 1099;
			_sizes[CZ_CHECK_PING] = 16;
			_sizes[CZ_CANCEL_INDUN_MATCHING] = 10;
			_sizes[CZ_CANCEL_INDUN_PARTY_MATCHING] = 10;
			_sizes[CZ_REQ_GM_ORDER] = 202;
			_sizes[CZ_REPORT_AUTOBOT] = 74;
			_sizes[CZ_REPORT_PVP_ZOOM] = 10;
			_sizes[CZ_PARTY_INVENTORY_LOAD] = 12;
			_sizes[CZ_PARTY_SHARED_QUEST] = 278;
			_sizes[CZ_REQ_MOVE_PARTYINV_TO_ACCOUNT] = 0;
			_sizes[CZ_PVP_COMMAND] = 23;
			_sizes[CZ_REQ_CancelGachaCube] = 10;
			_sizes[CZ_WAREHOUSE_TAKE_LIST] = 0;
			_sizes[CZ_SAVE_AUTO_MACRO] = 0;
			_sizes[CZ_REQUEST_LOAD_ITEM_BUY_LIMIT] = 10;
			_sizes[CZ_AUTO_STATE] = 11;
			_sizes[CZ_RUN_GAMEEXIT_TIMER] = 42;
			_sizes[CZ_FIXED_NOTICE_SHOW] = 10;
			_sizes[CZ_SAGE_SKILL_GO_FRIEND] = 90;
			_sizes[CZ_REQUEST_CHANGE_NAME] = 66;
			_sizes[CZ_REQUEST_CHANGE_PET_NAME] = 50;
			_sizes[CZ_CYOU_CTU_CLIENT_MSG] = 1054;
			_sizes[ZC_CYOU_KICK_USER_EXIT_CLIENT] = 10;
			_sizes[ZC_HOLD_EXP_BOOK_TIME] = 25;
			_sizes[CZ_HOLD_EXP_BOOK_TIME] = 14;
			_sizes[CZ_SCREENSHOT_HASH] = 43;
			_sizes[CZ_REQ_MOVE_TO_INDUN] = 18;
			_sizes[CZ_CLEAR_INDUN_REG] = 10;
			_sizes[CZ_REQ_REGISTER_TO_INDUN] = 14;
			_sizes[CZ_REQ_GUILD_MEMBER_AUTHORITY] = 23;
			_sizes[CZ_TPSHOP_RTPP_FOR_TEST] = 10;
			_sizes[CZ_REQ_FORGERY] = 30;
			_sizes[CZ_REQ_UNDERSTAFF_ENTER_ALLOW] = 10;
			_sizes[CZ_REQ_UNDERSTAFF_ENTER_ALLOW_WITH_PARTY] = 14;
			_sizes[CZ_REQ_BUILD_FOODTABLE] = 79;
			_sizes[ZC_PLAY_PAIR_ANIMATION] = 38;
			_sizes[CZ_REQ_FISHING] = 23;
			_sizes[CZ_REQ_GET_FISHING_ITEM] = 10;
			_sizes[ZC_PLAY_ATTACH_MODEL_ANIM] = 26;
			_sizes[CZ_RUN_FUNCTION_DUMP] = 0;
			_sizes[ZC_RUN_FUNCTION_DUMP] = 0;
			_sizes[ZC_RUN_FUNCTION_DUMP_ERROR] = 0;
			_sizes[ZC_RUN_FUNCTION_DUMP_PRINT] = 0;
			_sizes[ZC_ATTACH_TO_SLOT] = 26;
			_sizes[ZC_FISHING_ITEM_LIST] = 0;
			_sizes[CZ_REQ_FISHING_RANK] = 78;
			_sizes[ZC_ENABLE_ROTATE] = 79;
			_sizes[CZ_SYNC_POS] = 26;
			_sizes[ZC_ADVENTURE_BOOK_INFO] = 0;
			_sizes[CZ_DISCONNECT_REASON_FOR_LOG] = 0;
			_sizes[CZ_REQ_ADVENTURE_BOOK_RANK] = 142;
			_sizes[CZ_REQ_ADVENTURE_BOOK_REWARD] = 74;
			_sizes[CZ_REQ_GUILD_NEUTRALITY_ALARM] = 14;
			_sizes[CZ_REQ_QUEST_COMPLETE] = 14;
			_sizes[CZ_REQ_GUILD_ASSET_LOG] = 10;
			_sizes[ZC_COLONY_OCCUPATION_INFO] = 0;
			_sizes[ZC_BROAD_CAST_MY_INFO] = 30;
			_sizes[CZ_REQ_RETURN_TO_CITY_FROM_COLONY_WAR] = 10;
			_sizes[CZ_LOAD_COMPLETE] = 10;
			_sizes[ZC_LOAD_COMPLETE] = 10;
			_sizes[CZ_ACCEPT_CHALLENGE_MODE] = 14;
			_sizes[CZ_ACCEPT_NEXT_LEVEL_CHALLENGE_MODE] = 14;
			_sizes[CZ_ACCEPT_STOP_LEVEL_CHALLENGE_MODE] = 14;
			_sizes[ZC_UPDATE_CHALLENGE_MODE_WARP_PORTAL_MARK] = 23;
			_sizes[ZC_ATTENDANCE_RECEIPT_REWARD] = 0;
			_sizes[CZ_REGISTER_NEW_GUILD_EMBLEM] = 20095;
			_sizes[CZ_CHANGE_GUILD_EMBLEM] = 20096;
			_sizes[ZC_UPDATE_GUILD_EMBLEM] = 24;
			_sizes[CZ_REQUEST_CERTAIN_GUILD_EMBLEM] = 20;
			_sizes[ZC_RESPONSE_CERTAIN_GUILD_EMBLEM] = 20040;
			_sizes[CZ_REQUEST_GUILD_EMBLEM_INFO] = 20;
			_sizes[ZC_RESPONSE_GUILD_EMBLEM_INFO] = 102;
			_sizes[CZ_REQUEST_GUILD_INDEX] = 18;
			_sizes[ZC_RESPONSE_GUILD_INDEX] = 24;
			_sizes[CZ_REPORT_GUILDEMBLEM] = 74;
			_sizes[ZC_DELETE_GUILD_EMBLEM] = 24;
			_sizes[ZC_NXA_REQ_TICKET] = 10;
			_sizes[CZ_NXA_TICKET] = 1034;
			_sizes[CZ_NXA_REQ_BALANCE] = 10;
			_sizes[ZC_NXA_BALANCE] = 40;
			_sizes[CZ_NXA_REQ_ITEMLIST] = 11;
			_sizes[ZC_NXA_ITEMLIST] = 0;
			_sizes[CZ_NXA_REQ_PURCHASE] = 15;
			_sizes[ZC_NXA_PURCHASE] = 1034;
			_sizes[CZ_NXA_REQ_PICKUP_READY_ITEMS] = 523;
			_sizes[CZ_NXA_REQ_PURCHASE_CANCEL] = 10;
			_sizes[ZC_NXA_SELLITEMLIST] = 0;
			_sizes[CZ_REQ_PARTY_INFO] = 10;
			_sizes[CZ_REQ_RETURN_ORIGIN_SERVER] = 10;
			_sizes[CZ_ANS_GIVEUP_PREV_PLAYING_INDUN] = 11;
			_sizes[CZ_BADPLAYER_REPORT] = 146;
			_sizes[ZC_ERROR_INFO] = 78;
			_sizes[ZC_SEND_JSON_DUMP] = 0;
			_sizes[CZ_SEND_JSON_DUMP] = 0;

			foreach (var field in typeof(Op).GetFields(BindingFlags.Public | BindingFlags.Static))
				_names[(int)field.GetValue(null)] = field.Name;
		}

		public static int GetSize(int op)
		{
			if (!_sizes.TryGetValue(op, out var size))
				return -1;
			return size;
		}

		public static string GetName(int op)
		{
			if (!_names.TryGetValue(op, out var name))
				return "?";
			return name;
		}
	}
}
