// Melia
// Configuration file
//----------------------------------------------------------------------------

host     : 127.0.0.1
port     : 3306
user     : root
pass     : 
database : melia

include "/user/conf/database.conf"
