ALTER TABLE `characters` ADD `zone` INT NOT NULL AFTER `level`;
ALTER TABLE `characters` ADD `exp` INT NOT NULL DEFAULT '0' , ADD `maxExp` INT NOT NULL DEFAULT '1000' , ADD `hp` INT NOT NULL DEFAULT '100' , ADD `maxHp` INT NOT NULL DEFAULT '100' , ADD `sp` INT NOT NULL DEFAULT '50' , ADD `maxSp` INT NOT NULL DEFAULT '50' , ADD `stamina` INT NOT NULL DEFAULT '50000' ;
