Melia.Ui.SysMenu.Clear()

Melia.Ui.SysMenu.AddButton("BtnSystem", "sysmenu_sys", "System Menu (Esc)", "ui.ToggleFrame('apps')")
Melia.Ui.SysMenu.AddButton("BtnCollection", "sysmenu_coll", "Collection (F11)", "UI_TOGGLE_COLLECTION()")
Melia.Ui.SysMenu.AddButton("BtnInstantDungeon", "sysmenu_instantDungeon", "Contents Status Board (F10)", "UI_TOGGLE_INDUN()")
Melia.Ui.SysMenu.AddButton("BtnPet", "sysmenu_pet", "Companion (F9)", "UI_TOGGLE_PETLIST()")
Melia.Ui.SysMenu.AddButton("BtnMacro", "sysmenu_mac", "Macro (F8)", "UI_TOGGLE_POSE_MACRO()")
Melia.Ui.SysMenu.AddButton("BtnFriends", "sysmenu_friend", "Friends (F7)", "ui.ToggleFrame('friend')")
Melia.Ui.SysMenu.AddButton("BtnParty", "sysmenu_party", "Party", "ui.ToggleFrame('partyapps')")
Melia.Ui.SysMenu.AddButton("BtnQuests", "sysmenu_jal", "Quests (F5)", "ui.ToggleFrame('quest')")
Melia.Ui.SysMenu.AddButton("BtnJournal", "sysmenu_qu", "Achievement/Adventure Journal (F4)", "ui.ToggleFrame('adventure_book')")
Melia.Ui.SysMenu.AddButton("BtnSkills", "sysmenu_skill", "Skills and Attributes (F3)", "ui.ToggleFrame('skillability')")
Melia.Ui.SysMenu.AddButton("BtnInventory", "sysmenu_inv", "Inventory (F2)", "ui.ToggleFrame('inventory')")
Melia.Ui.SysMenu.AddButton("BtnStatus", "sysmenu_my", "Character Information (F1)", "ui.ToggleFrame('status')")
Melia.Ui.SysMenu.AddButton("BtnAdvancement", "sysmenu_jobinfo", "Advancement Info", "OPEN_RANKROLLBACK_UI_BY_SYSMENU()")
Melia.Ui.SysMenu.AddButton("BtnFishing", "sysmenu_Fishing", "Tackle Box (Alt + F)", "FISHING_ITEM_BAG_TOGGLE()")
Melia.Ui.SysMenu.AddButton("BtnGuildPromo", "sysmenu_guild_rank", "Guild Promotion (Alt + R)", "GUILD_RANK_INFO_TOGGLE()")
Melia.Ui.SysMenu.AddButton("BtnPcBang", "sysmenu_pp", "Popo Shop", "ui.ToggleFrame('pcbang_shop')()")
