// Melia
// Configuration file
//----------------------------------------------------------------------------

// If enabled, monster AIs will utilize pathfinding to reach their target.
// Requires server restart.
monsters_use_pathfinding: yes

// If enabled, monsters can may freely wander the maps and don't restrict
// random movement to their spawn area.
free_roam_monsters: no

// If enabled, monsters will return to their spawn point if they get lured
// away.
monsters_return_home: yes

include "/user/conf/world/ai.conf"
