// Melia
// Configuration file
//----------------------------------------------------------------------------

// Minimum and maximum respawn delay in seconds if no respawn time was
// set for a spawner. Set to 0 to respawn monsters immediately after
// death.
default_min_respawn: 30
default_max_respawn: 60

include "/user/conf/world/monsters.conf"
